### PR TITLE
Issue #1296 Fix preflight check for kvm driver

### LINKED ISSUE #1296: Pre-flight check for docker-machine-driver-kvm misses bad permissions
i ended up w/ a docker-machine-driver-kvm that was only executable by root. the result was minishift start would pass pre-flight checks and fail during VM start w/ an unrelated message -

```
-- Starting Minishift VM ... / FAIL E0822 11:40:58.269341   31343 start.go:342] Error starting the VM: Error attempting to get plugin server address for RPC: Failed to dial the plugin server in 10s. Retrying.
\ FAIL E0822 11:41:08.270398   31343 start.go:342] Error starting the VM: Error attempting to get plugin server address for RPC: Failed to dial the plugin server in 10s. Retrying.
/ FAIL E0822 11:41:18.271489   31343 start.go:342] Error starting the VM: Error attempting to get plugin server address for RPC: Failed to dial the plugin server in 10s. Retrying.
Error starting the VM: Error attempting to get plugin server address for RPC: Failed to dial the plugin server in 10s
Error attempting to get plugin server address for RPC: Failed to dial the plugin server in 10s
Error attempting to get plugin server address for RPC: Failed to dial the plugin server in 10s
```

the fix is to properly install the driver (chmod a+x), however the pre-flight check should detect and warn of this.

### PR DESCRIPTION
**Pull request by praveenkumar**
Fix #1296

### CODE REVIEW

File: cmd/minishift/cmd/start_preflight.go [hunk 1]
```diff
@@ -209,8 +209,20 @@ func checkKvmDriver() bool {
...
+	if fi.Mode()&os.ModeSymlink != 0 {
+		path, err = os.Readlink(path)
+		if err != nil {
+			return false
+		}
+	}
+	fmt.Println(fmt.Sprintf("\n   Driver is available at %s ... ", path))
 
+	fmt.Printf("   Checking for execute bit ...")
+	if fi.Mode()&0011 == 0 {
```
Comment (LalatenduMohanty) [inline cmd/minishift/cmd/start_preflight.go]: I am not sure about this. Any pointers to understand this better.

Comment (gbraad) [reply cmd/minishift/cmd/start_preflight.go]: https://golang.org/pkg/os/#FileMode

File: cmd/minishift/cmd/start_preflight.go [hunk 2]
```diff
@@ -209,8 +209,20 @@ func checkKvmDriver() bool {
 	if err != nil {
 		return false
 	}
-	fmt.Printf(fmt.Sprintf("\n   Driver is available at %s ... ", path))
+	fi, _ := os.Stat(path)
+	// follow symlinks
```
[the remark this answers is not in the document]
Comment (gbraad) [reply cmd/minishift/cmd/start_preflight.go]: This is taken from the macOS (xhyve) implementation. follow symlinks means it will check if the symlink exists and else error out.

File: cmd/minishift/cmd/start_preflight.go (hunk 1 above)
Comment (LalatenduMohanty) [reply cmd/minishift/cmd/start_preflight.go]: @gbraad I am not sure how `fi.Mode()&0011 ` give us the correct result i.e.fi.Mode() returns  -rwxr-xr-x and we are doing a `&` operation with `0011`. I found https://groups.google.com/forum/#!topic/golang-nuts/_6YqjJdfYyA but still do not understand completely.

File: cmd/minishift/cmd/start_preflight.go [hunk 3]
```diff
@@ -209,8 +209,20 @@ func checkKvmDriver() bool {
...
+	if fi.Mode()&os.ModeSymlink != 0 {
+		path, err = os.Readlink(path)
+		if err != nil {
+			return false
+		}
+	}
+	fmt.Println(fmt.Sprintf("\n   Driver is available at %s ... ", path))
 
+	fmt.Printf("   Checking for execute bit ...")
```
Comment (LalatenduMohanty) [inline cmd/minishift/cmd/start_preflight.go]: 👍

File: cmd/minishift/cmd/start_preflight.go (hunk 2 above)
[the remark this answers is not in the document]
Comment (LalatenduMohanty) [reply cmd/minishift/cmd/start_preflight.go]: I think we can just remove the comment as the code is simple to read.

File: cmd/minishift/cmd/start_preflight.go (hunk 1 above)
Comment (gbraad) [reply cmd/minishift/cmd/start_preflight.go]: it is masking the bits for ModePerm. some libraries like go-permbits are a little bit more intuitive. but it is just bitshifted and OR-ed. it checks that o+x and g+x is set.

https://golang.org/src/os/types.go#L35

File: cmd/minishift/cmd/start_preflight.go (hunk 2 above)
[the remark this answers is not in the document]
Comment (gbraad) [reply cmd/minishift/cmd/start_preflight.go]: if so, I would suggest to refactor the both usages of the code to be a single function.

**Comment by budhrg** [comment]
I am not sure it is working as expected: 
```
$ minishift start
-- Checking if KVM driver is installed ... 
   Driver is available at /usr/local/bin/docker-machine-driver-kvm ... 
   Checking for execute bit ...OK
-- Starting local OpenShift cluster using 'kvm' hypervisor ...
-- Minishift VM will be configured with ...
   Memory:    2 GB
   vCPUs :    2
   Disk size: 20 GB

   Downloading ISO 'https://github.com/minishift/minishift-b2d-iso/releases/download/v1.1.0/minishift-b2d.iso'
 40.00 MiB / 40.00 MiB [==========================================================================================================================================================] 100.00% 0s
-- Starting Minishift VM ... / FAIL E0831 21:44:07.921519    4385 start.go:344] Error starting the VM: Error attempting to get plugin server address for RPC: Failed to dial the plugin server in 10s. Retrying.
\ FAIL E0831 21:44:17.925371    4385 start.go:344] Error starting the VM: Error attempting to get plugin server address for RPC: Failed to dial the plugin server in 10s. Retrying.
/ FAIL E0831 21:44:27.926424    4385 start.go:344] Error starting the VM: Error attempting to get plugin server address for RPC: Failed to dial the plugin server in 10s. Retrying.
Error starting the VM: Error attempting to get plugin server address for RPC: Failed to dial the plugin server in 10s
Error attempting to get plugin server address for RPC: Failed to dial the plugin server in 10s
Error attempting to get plugin server address for RPC: Failed to dial the plugin server in 10s


# Permissions
$ ls /usr/local/bin/docker-machine-driver-kvm -lsh
12M -rwxr-xr--. 1 root root 12M Jan 12  2017 /usr/local/bin/docker-machine-driver-kvm
```

How did you test it @praveenkumar ?

**Comment by gbraad** [comment]
Are you a member of the `libvirt` group ?
Note: This is a test we can not perform

File: cmd/minishift/cmd/start_preflight.go (hunk 3 above)
Comment (gbraad) [reply cmd/minishift/cmd/start_preflight.go]:
```diff
-fmt.Printf("   Checking for execute bit ...")
+fmt.Printf("   Checking for execute bit ... ")
```

**Comment by budhrg** [comment]
> Are you a member of the libvirt group ?
Note: This is a test we can not perform

My bad @gbraad here. I only changed the executed bit for other. On removing executable for current user, I am getting the expected error :smile: 

```
$ groups
budhram libvirt

$ ls /usr/local/bin/docker-machine-driver-kvm -l
-r-xr--r--. 1 root root 12096944 Jan 12  2017 /usr/local/bin/docker-machine-driver-kvm

$ minishift start
-- Checking if KVM driver is installed ... 
   Driver is available at /usr/local/bin/docker-machine-driver-kvm ... 
   Checking for execute bit ...FAIL
   See the 'Setting Up the Driver Plug-in' topic for more information
```

Looks good to me. 
However,  I think instead of `Checking for execute bit` , `Checking driver is executable ... FAIL` would read intuitive IMO.
WDYT @praveenkumar ?

File: cmd/minishift/cmd/start_preflight.go (hunk 3 above)
Comment (budhrg) [reply cmd/minishift/cmd/start_preflight.go]: @gbraad @praveenkumar , any thought on 
`fmt.Printf("   Checking driver is executable ... ")` 
?

File: cmd/minishift/cmd/start_preflight.go [hunk 4]
```diff
@@ -209,8 +209,20 @@ func checkKvmDriver() bool {
...
+	// follow symlinks
+	if fi.Mode()&os.ModeSymlink != 0 {
+		path, err = os.Readlink(path)
+		if err != nil {
+			return false
+		}
+	}
+	fmt.Println(fmt.Sprintf("\n   Driver is available at %s ... ", path))
 
+	fmt.Printf("   Checking driver binary is executable ... ")
```
Comment (budhrg) [inline cmd/minishift/cmd/start_preflight.go]: :+1:

Comment (gbraad) [reply cmd/minishift/cmd/start_preflight.go]: Not grammatically correct, but it is acceptable for now.
