### PR TITLE
Issue #1200 Refactor registration code

### LINKED ISSUE #1200: Possible error in stop/unregistration code
Related to #1121. When using a CentOS-based image, I have to use `--skip-unregistration` when SSH is not able to connect. In the case of a CentOS image, registration and deregistration should not checked for.

```
$ minishift start --iso-url centos
$ minishift ssh "sudo systemctl stop sshd"
$ minishift stop
Stopping local OpenShift cluster...
Error unregistering the VM: ssh command error:
command : sudo cat /etc/os-release
err     : exit status 255
output  : 
$ minishift start
The 'minishift' VM is already running.
$ minishift stop --skip-unregistration
Stopping local OpenShift cluster...
Cluster stopped.
```

### PR DESCRIPTION
**Pull request by gbraad**
Fixes #1200 

### Before
```
$ minishift start --iso-url centos
$ minishift ssh "sudo systemctl stop sshd"
$ minishift stop
Stopping local OpenShift cluster...
Error unregistering the VM: ssh command error:
command : sudo cat /etc/os-release
err     : exit status 255
output  : 
```

### After
```
$ minishift start --iso-url centos
$ minishift ssh "sudo systemctl stop sshd"
$ minishift delete
Deleting the Minishift VM...
Minishift VM deleted.
```

### CODE REVIEW

**Comment by budhrg** [comment]
@gbraad commit message is using `deregistration` instead of `unregistration` :smile:

File: cmd/minishift/cmd/stop.go [hunk 1]
```diff
@@ -62,11 +62,15 @@ func runStop(cmd *cobra.Command, args []string) {
 	fmt.Println("Stopping local OpenShift cluster...")
 
 	if !skipUnRegistration {
-		if _, err := cluster.UnRegister(api); err != nil {
+		supportRegistration, err := cluster.UnRegister(api)
```
Comment (budhrg) [inline cmd/minishift/cmd/stop.go]: How about `registrationSupport(ed)` ?

File: pkg/minikube/cluster/cluster.go [hunk 2]
```diff
@@ -152,15 +152,15 @@ func UnRegister(api libmachine.API) (bool, error) {
...
-		if err != nil {
-			return false, err
-		}
-	} else {
-		return true, nil
+	if !drivers.MachineInState(host.Driver, state.Running)() {
+		return true, fmt.Errorf("Unable to verify registration. VM not in running state")
+	}
+
+	supportUnregistration, err := registration.UnregisterHostVM(host, RegistrationParameters)
```
Comment (budhrg) [inline pkg/minikube/cluster/cluster.go]: Same here. `unregistrationSupport(ed)`.

**Comment by gbraad** [comment]
retest this please

File: cmd/minishift/cmd/stop.go (hunk 1 above)
Comment (gbraad) [inline cmd/minishift/cmd/stop.go]: this is consistent with the previous function we modified

**Comment by gbraad** [comment]
rebased on #660 to make sure SSH code is usable

**Comment by gbraad** [comment]
```
$ minishift ssh "sudo systemctl stop sshd"
$ minishift delete
Deleting the Minishift VM...
Minishift VM deleted.
```

File: cmd/minishift/cmd/stop.go [hunk 3]
```diff
@@ -61,12 +61,16 @@ func runStop(cmd *cobra.Command, args []string) {
 
 	fmt.Println("Stopping local OpenShift cluster...")
 
-	if !skipUnRegistration {
-		if _, err := cluster.UnRegister(api); err != nil {
+	if !skipUnRegistration && minishiftConfig.InstanceConfig.IsRegistered {
+		supportUnregistration, err := cluster.UnRegister(api)
```
Comment (hferentschik) [inline cmd/minishift/cmd/stop.go]: _supportUnregistration_  is an unfortunate name imo. It implies to me that whatever you call "checks" whether unregistration is supported. Judging by name, I would not expect that unregistration actually occurs. However, this is the case. Why not 'unregistered' or 'unregistrationSuccessful'. This also makes clear why we then clean up the instance config state.

Comment (hferentschik) [inline cmd/minishift/cmd/stop.go]: I think the problem is that we try to do two things here. Determine whether the VM supports un-registration as well as doing the actual un-registration.

File: pkg/minikube/cluster/cluster.go [hunk 4]
```diff
@@ -152,15 +152,15 @@ func UnRegister(api libmachine.API) (bool, error) {
...
 
-	if drivers.MachineInState(host.Driver, state.Running)() {
-		err := registration.UnregisterHostVM(host, RegistrationParameters)
-		if err != nil {
-			return false, err
-		}
-	} else {
-		return true, nil
+	if !drivers.MachineInState(host.Driver, state.Running)() {
+		return true, fmt.Errorf("Unable to verify registration. VM not in running state")
```
Comment (hferentschik) [inline pkg/minikube/cluster/cluster.go]: So why _true_? The VM is not running, so how do you know that it "supports" unregistration.

File: cmd/minishift/cmd/stop.go (hunk 3 above)
Comment (hferentschik) [inline cmd/minishift/cmd/stop.go]: Also, the whole point of 'minishiftConfig.InstanceConfig.IsRegistered' was to be able to handle the un-regristration case, for the case that the VM cannot be accessed. So assuming all data is in a consistent state the check for _minishiftConfig.InstanceConfig.IsRegistered_ already tells us that the VM supports (un)registration. So I think all that's needed is to handle the error a bit differently. 

We might want to align with the _delete_ command where in the case of a failing un-registration the user gets prompted on whether to processed or not. See https://github.com/minishift/minishift/blob/2335e6ac4aa252e7046070f2f8a5ca76675f12c3/cmd/minishift/cmd/delete.go#L54

File: pkg/minikube/cluster/cluster.go (hunk 4 above)
Comment (gbraad) [inline pkg/minikube/cluster/cluster.go]: We can also not return false. It is a tristate (true, false, unknown) since it does not allow only an error to be returned, the true is the least error-prone as we prevent to continue when the information is unclear.

File: cmd/minishift/cmd/stop.go (hunk 3 above)
Comment (gbraad) [inline cmd/minishift/cmd/stop.go]: If `minishiftConfig.InstanceConfig.IsRegistered` was the whole point, it seems we neglected to actually check the state of this variable. This is why this change is suggested.

Without checking this, it means that images like B2D and CentOS will always be requested about `supportRegistration`. If for some reason, deployment did not succeed in a working VM (no IP for instance), it becomes problematic for the user to stop (or delete) the VM. This should never happen...

Comment (hferentschik) [inline cmd/minishift/cmd/stop.go]: > If minishiftConfig.InstanceConfig.IsRegistered was the whole point, it seems we neglected to actually check the state of this variable.

That's correct. It should have been checked. Similar to the delete _command_.

> This is why this change is suggested/issue got filed.

Sure. I am not saying there is no issue here. I am just saying that if _minishiftConfig.InstanceConfig.IsRegistered_ is _true_, we already know that _supportUnregistration_ is true.

**Comment by gbraad** [comment]
Will consider to refactor some of this code, as I am not happy how it lives inside `cluster.go` and the possible duplication between `delete` and `stop` command.

File: cmd/minishift/cmd/stop.go (hunk 3 above)
Comment (praveenkumar) [inline cmd/minishift/cmd/stop.go]: >If minishiftConfig.InstanceConfig.IsRegistered was the whole point, it seems we neglected to actually check the state of this variable.

@gbraad right it was missed from my sight when implementing `minishiftConfig.InstanceConfig.IsRegistered` flag and should be handled same as delete command which only look for that variable.

**Comment by hferentschik** [comment]
> as I am not happy how it lives inside cluster.go and the possible duplication between delete and stop command.

+1

**Comment by gbraad** [comment]
@praveenkumar @hferentschik open to comments...

**Comment by gbraad** [comment]
```
-- Checking if KVM driver is installed ... 
   Driver is available at /usr/local/bin/docker-machine-driver-kvm ... OK
-- Starting local OpenShift cluster using 'kvm' hypervisor ...
-- Minishift VM will be configured with ...
   Memory:    2 GB
   vCPUs :    2
   Disk size: 20 GB
-- Starting Minishift VM ... OK
Registering machine using subscription-manager
Red Hat Developers or Red Hat Subscription Management (RHSM) username: gbraad
Red Hat Developers or Red Hat Subscription Management (RHSM) password: [HIDDEN]
Registration successful [43.9s]
-- Checking for IP address ... OK
-- Checking if external host is reachable from the Minishift VM ... 
   Pinging 8.8.8.8 ... OK
-- Checking HTTP connectivity from the VM ... 
   Retrieving http://minishift.io/index.html ... OK
-- Checking if persistent storage volume is mounted ... OK
-- Checking available disk space ... 1% OK
```

Do I need to change the lines:

```
Registering machine using subscription-manager
Red Hat Developers or Red Hat Subscription Management (RHSM) username: gbraad
Red Hat Developers or Red Hat Subscription Management (RHSM) password: [HIDDEN]
Registration successful [43.9s]
```
to represent the same output as the rest?

File: cmd/minishift/cmd/registration.go [hunk 5]
```diff
@@ -0,0 +1,81 @@
...
+	// if continued, we remove the IsRegistered state
+	setRegistered(false)
+}
+
+func handleFailedRegistrationAction() {
+	hasConfirmed := pkgUtil.AskForConfirmation("Current Minishift VM is registered, but unregistration failed.")
+	if !hasConfirmed {
+		atexit.ExitWithMessage(0, fmt.Sprintln("Aborted."))
+	}
+}
```
Comment (praveenkumar) [inline cmd/minishift/cmd/registration.go]: much better 👍

File: cmd/minishift/cmd/start.go [hunk 6]
```diff
@@ -588,10 +587,10 @@ func validateOpenshiftVersion() {
...
 
 func setSubscriptionManagerParameters() {
-	cluster.RegistrationParameters.Username = viper.GetString(configCmd.Username.Name)
-	cluster.RegistrationParameters.Password = viper.GetString(configCmd.Password.Name)
-	cluster.RegistrationParameters.GetUsernameInteractive = getUsernameInteractive
-	cluster.RegistrationParameters.GetPasswordInteractive = getPasswordInteractive
+	minishiftCluster.RegistrationParameters.Username = viper.GetString(configCmd.Username.Name)
+	minishiftCluster.RegistrationParameters.Password = viper.GetString(configCmd.Password.Name)
+	minishiftCluster.RegistrationParameters.GetUsernameInteractive = getUsernameInteractive
+	minishiftCluster.RegistrationParameters.GetPasswordInteractive = getPasswordInteractive
```
Comment (praveenkumar) [inline cmd/minishift/cmd/start.go]: Nice no more depend on minikube/cluster 👍

File: pkg/minishift/cluster/registration.go [hunk 7]
```diff
@@ -0,0 +1,56 @@
...
+
+// Register returns true if successfully registered
+func Register(api libmachine.API) (bool, error) {
+	return doRegistrationAction(api, registration.RegisterHostVM)
+}
+
+// UnRegister returns true if successfully unregistered
+func UnRegister(api libmachine.API) (bool, error) {
+	return doRegistrationAction(api, registration.UnregisterHostVM)
+}
```
Comment (praveenkumar) [inline pkg/minishift/cluster/registration.go]: 👍

File: cmd/minishift/cmd/start.go (hunk 6 above)
Comment (gbraad) [inline cmd/minishift/cmd/start.go]: Pretty sure we can now even reduce the code slightly further... But some other time maybe?

File: cmd/minishift/cmd/registration.go [hunk 8]
```diff
@@ -0,0 +1,81 @@
...
+	pkgUtil "github.com/minishift/minishift/pkg/util"
+	"github.com/minishift/minishift/pkg/util/os/atexit"
+)
+
+var (
+	skipRegistration   bool
+	skipUnRegistration bool
+)
+
+func isRegistered() bool {
```
Comment (hferentschik) [inline cmd/minishift/cmd/registration.go]: 👍

File: cmd/minishift/cmd/registration.go [hunk 9]
```diff
@@ -0,0 +1,81 @@
...
+	return minishiftConfig.InstanceConfig.IsRegistered
+}
+
+func setRegistered(state bool) {
```
Comment (hferentschik) [inline cmd/minishift/cmd/registration.go]: 👍

File: cmd/minishift/cmd/registration.go [hunk 10]
```diff
@@ -0,0 +1,81 @@
...
+func registerHost(libMachineClient *libmachine.Client) {
+	if skipRegistration {
+		log.Debug("Skipping registration due to enabled '--skip-registration' flag")
+		return
+	}
+
+	if wasSuccessful, err := cluster.Register(libMachineClient); err != nil {
+		atexit.ExitWithMessage(1, fmt.Sprintf("Error to register VM: %v", err))
+	} else {
+		// else, we set the IsRegistered state according to result
```
Comment (hferentschik) [inline cmd/minishift/cmd/registration.go]: :+1
