### PR TITLE
Issue #2063 Fix cert permission for minikube ISO

### LINKED ISSUE #2063: Permission of certificates is altered after using the Minikube provisioner
### General information

  * Minishift version: v1.7.0+ (Since we start support of Minikube ISO) 
  * OS: Windows
  * Hypervisor: Hyper-V / Virtualbox

### Steps to reproduce

  1. `minishift.exe start --iso-url minikube`

### Expected

Minikube ISO should work.

### Actual

Minikube ISO fails to start minishift VM.

### Logs

```
PS C:\> minishift.exe version
minishift v1.7.0+1549135

PS C:\> minishift.exe start --iso-url minikube
-- Checking if Hyper-V driver is installed ... OK
-- Checking if Hyper-V driver is configured to use a Virtual Switch ... OK
-- Checking if user is a member of the Hyper-V Administrators group ... OK
-- Starting local OpenShift cluster using 'hyperv' hypervisor ...
-- Minishift VM will be configured with ...
   Memory:    2 GB
   vCPUs :    2
   Disk size: 20 GB

   Downloading ISO 'https://storage.googleapis.com/minikube/iso/minikube-v0.24.0.iso'
 141.81 MiB / 141.81 MiB [=================================================================================================================================] 100.00% 0s
-- Starting Minishift VM ......................................................... FAIL E0223 17:17:23.720221    1592 start.go:355] Error starting the VM: Error creating the VM. Error creating machine: Error running provisioning: Temporary Error: transferring file: &{BaseAsset:{data:[] reader:0xc0422de018 Length:0 AssetName:C:\Users\budhram\.minishift\certs\ca.pem TargetDir:C:\Users\budhram\.minishift TargetName:ca.pem Permissions:0777}}: error changing file permissions for C:\Users\budhram\.minishift\ca.pem: chmod C:\Users\budhram\.minishift\ca.pem: not supported by windows
Temporary Error: transferring file: &{BaseAsset:{data:[] reader:0xc04211e028 Length:0 AssetName:C:\Users\budhram\.minishift\certs\cert.pem TargetDir:C:\Users\budhram\.minishift TargetName:cert.pem Permissions:0777}}: error changing file permissions for C:\Users\budhram\.minishift\cert.pem: chmod C:\Users\budhram\.minishift\cert.pem: not supported by windows
Temporary Error: transferring file: &{BaseAsset:{data:[] reader:0xc042110038 Length:0 AssetName:C:\Users\budhram\.minishift\certs\ca.pem TargetDir:C:\Users\budhram\.minishift TargetName:ca.pem Permissions:0777}}: error removing file C:\Users\budhram\.minishift\ca.pem: remove C:\Users\budhram\.minishift\ca.pem: The process cannot access the file because it is being used by another process.
Temporary Error: transferring file: &{BaseAsset:{data:[] reader:0xc04211e050 Length:0 AssetName:C:\Users\budhram\.minishift\certs\key.pem TargetDir:C:\Users\budhram\.minishift TargetName:key.pem Permissions:0777}}: error changing file permissions for C:\Users\budhram\.minishift\key.pem: chmod C:\Users\budhram\.minishift\key.pem: not supported by windows
Temporary Error: transferring file: &{BaseAsset:{data:[] reader:0xc04211e070 Length:0 AssetName:C:\Users\budhram\.minishift\certs\cert.pem TargetDir:C:\Users\budhram\.minishift TargetName:cert.pem Permissions:0777}}: error removing file C:\Users\budhram\.minishift\cert.pem: remove C:\Users\budhram\.minishift\cert.pem: The process cannot access the file because it is being used by another process.. Retrying.
Error starting the VM: Error creating the VM. Error creating machine: Error running provisioning: Temporary Error: transferring file: &{BaseAsset:{data:[] reader:0xc0422de018 Length:0 AssetName:C:\Users\budhram\.minishift\certs\ca.pem TargetDir:C:\Users\budhram\.minishift TargetName:ca.pem Permissions:0777}}: error changing file permissions for C:\Users\budhram\.minishift\ca.pem: chmod C:\Users\budhram\.minishift\ca.pem: not supported by windows
Temporary Error: transferring file: &{BaseAsset:{data:[] reader:0xc04211e028 Length:0 AssetName:C:\Users\budhram\.minishift\certs\cert.pem TargetDir:C:\Users\budhram\.minishift TargetName:cert.pem Permissions:0777}}: error changing file permissions for C:\Users\budhram\.minishift\cert.pem: chmod C:\Users\budhram\.minishift\cert.pem: not supported by windows
Temporary Error: transferring file: &{BaseAsset:{data:[] reader:0xc042110038 Length:0 AssetName:C:\Users\budhram\.minishift\certs\ca.pem TargetDir:C:\Users\budhram\.minishift TargetName:ca.pem Permissions:0777}}: error removing file C:\Users\budhram\.minishift\ca.pem: remove C:\Users\budhram\.minishift\ca.pem: The process cannot access the file because it is being used by another process.
Temporary Error: transferring file: &{BaseAsset:{data:[] reader:0xc04211e050 Length:0 AssetName:C:\Users\budhram\.minishift\certs\key.pem TargetDir:C:\Users\budhram\.minishift TargetName:key.pem Permissions:0777}}: error changing file permissions for C:\Users\budhram\.minishift\key.pem: chmod C:\Users\budhram\.minishift\key.pem: not supported by windows
Temporary Error: transferring file: &{BaseAsset:{data:[] reader:0xc04211e070 Length:0 AssetName:C:\Users\budhram\.minishift\certs\cert.pem TargetDir:C:\Users\budhram\.minishift TargetName:cert.pem Permissions:0777}}: error removing file C:\Users\budhram\.minishift\cert.pem: remove C:\Users\budhram\.minishift\cert.pem: The process cannot access the file because it is being used by another process.
```

### PR DESCRIPTION
**Pull request by praveenkumar**
Fixes #2063 and #2098

### CODE REVIEW

**Comment by gbraad** [comment]
This is NOT Windows specific... I also experience(d) this on Linux

**Comment by praveenkumar** [comment]
@gbraad updated the commit message.

**Comment by anjannath** [comment]
So the original issue seems to get fixed by this PR, Now able to start the VM using minikube iso, but while using origin `v3.9.0`  got issue #2222 

Using origin `v3.7.2` origin started successfully but getting issue #1993 while trying to deploy app.

File: pkg/minishift/provisioner/buildroot_provisioner.go [hunk 1]
```diff
@@ -83,28 +83,40 @@ func (p *BuildrootProvisioner) Provision(swarmOptions swarm.Options, authOptions
...
+		log.Info("OK")
 	}
 
-	p.AuthOptions = setRemoteAuthOptions(p)
-	log.Debugf("set auth options %+v", p.AuthOptions)
+	if err := makeDockerOptionsDir(p); err != nil {
+		return err
+	}
+
+	dockerCfg, err := p.GenerateDockerOptions(engine.DefaultPort)
```
Comment (budhrg) [inline pkg/minishift/provisioner/buildroot_provisioner.go]: Line 98-107 seems to be repeated in `provision.ConfigureAuth` function.
See https://github.com/minishift/minishift/blob/52b35d0a4f5119bb9843d5712d7e7fd1e5f6dd70/pkg/minishift/provisioner/utils.go#L252-L261

File: pkg/minishift/provisioner/buildroot_provisioner.go [hunk 2]
```diff
@@ -83,28 +83,40 @@ func (p *BuildrootProvisioner) Provision(swarmOptions swarm.Options, authOptions
...
-		}
-		return nil
+	if _, err = p.SSHCommand(fmt.Sprintf("sudo mkdir -p %s && printf %%s \"%s\" | sudo tee %s", path.Dir(dockerCfg.EngineOptionsPath), dockerCfg.EngineOptions, dockerCfg.EngineOptionsPath)); err != nil {
+		return err
 	}
 
-	err := util.RetryAfter(5, configureAuth, time.Second*10)
-	if err != nil {
-		log.Debugf("Error configuring auth during provisioning %v", err)
+	if _, err = p.SSHCommand("sudo systemctl -f daemon-reload"); err != nil {
```
Comment (budhrg) [inline pkg/minishift/provisioner/buildroot_provisioner.go]: So, only this seems to the piece of the puzzle which was required. 
It would be good to have a comment here why it is required.

File: pkg/minishift/provisioner/buildroot_provisioner.go (hunk 1 above)
Comment (praveenkumar) [reply pkg/minishift/provisioner/buildroot_provisioner.go]: If you check this PR, I removed this function because we were using it as minikube does and it was not working for us anymore.

File: pkg/minishift/provisioner/buildroot_provisioner.go (hunk 2 above)
Comment (praveenkumar) [reply pkg/minishift/provisioner/buildroot_provisioner.go]: This is required because by default minikube iso doesn't have any service file and this is required in after we generate service file.

**Comment by anjannath** [comment]
@praveenkumar After the latest commits, able to start origin `v3.9.0`, but still seeing the app deployment issue #1993

**Comment by budhrg** [comment]
> So the original issue seems to get fixed by this PR, Now able to start the VM using minikube iso, but while using origin v3.9.0 got issue #2222

Yes, original issue of starting Minishift VM and #2222 seems to be fixed but still able to reproduce #1993 while deploying an application.

File: pkg/minishift/provisioner/buildroot_provisioner.go [hunk 3]
```diff
@@ -83,28 +83,45 @@ func (p *BuildrootProvisioner) Provision(swarmOptions swarm.Options, authOptions
 	p.AuthOptions = authOptions
 	p.EngineOptions = engineOptions
 
-	log.Debugf("setting hostname %q", p.Driver.GetMachineName())
+	log.Info("\n   Setting hostname ... ")
```
Comment (LalatenduMohanty) [inline pkg/minishift/provisioner/buildroot_provisioner.go]: Why are we changing the log level here?

File: pkg/minishift/provisioner/buildroot_provisioner.go [hunk 4]
```diff
@@ -83,28 +83,45 @@ func (p *BuildrootProvisioner) Provision(swarmOptions swarm.Options, authOptions
...
+	// This is something we should do as part of ISO but atm not able to find a pointer [PK]
+	if _, err = p.SSHCommand("sudo ln -sfn /run/systemd/resolve/resolv.conf /etc/resolv.conf"); err != nil {
+		return err
+	}
+	p.AuthOptions = setRemoteAuthOptions(p)
 
-	err := util.RetryAfter(5, configureAuth, time.Second*10)
-	if err != nil {
-		log.Debugf("Error configuring auth during provisioning %v", err)
+	if err := provision.ConfigureAuth(p); err != nil {
```
Comment (LalatenduMohanty) [inline pkg/minishift/provisioner/buildroot_provisioner.go]: So we are failing back to libmachine for ConfigureAuth.

**Comment by LalatenduMohanty** [comment]
> I suggest to disable systemd-resolved

+1

File: pkg/minishift/provisioner/buildroot_provisioner.go (hunk 3 above)
Comment (gbraad) [reply pkg/minishift/provisioner/buildroot_provisioner.go]: to make it part of the actual output

File: pkg/minishift/provisioner/buildroot_provisioner.go [hunk 5]
```diff
@@ -83,28 +83,45 @@ func (p *BuildrootProvisioner) Provision(swarmOptions swarm.Options, authOptions
...
 		return err
 	}
 
+	doFeatureDetection(p)
```
Comment (gbraad) [inline pkg/minishift/provisioner/buildroot_provisioner.go]: +1

**Comment by gbraad** [comment]
`systemd-resolved` will be disabled in a different PR (as part of the ISO)

**Comment by LalatenduMohanty** [comment]
> systemd-resolved will be disabled in a different PR (as part of the ISO)

Do we have an issue number?

**Comment by gbraad** [comment]
This is filed at minikube...
