### PR TITLE
Issue #2454 Fix check for Default Switch

### LINKED ISSUE #2454: Correct the code for default switch check for HyperV
The environment variable does not exist anymore

https://github.com/minishift/minishift/blob/1426bddcbf7aae0b8fab29dbe28b667a9ae218cb/pkg/minishift/network/settings_windows.go#L43

### PR DESCRIPTION
**Pull request by anjannath**
Fixes #2454 #2885 

One way to test if this is working properly.. start minishift in windows using the `Default Switch` and provide an IP address for it, `minishift` will try to guess the netmask, and if this works as expected the netmask should be `225.255.255.240`

### CODE REVIEW

File: pkg/minishift/network/settings_windows.go [hunk 1]
```diff
@@ -41,10 +42,8 @@ var (
 )
 
 func isUsingDefaultSwitch() bool {
-	switchEnvName := "HYPERV_VIRTUAL_SWITCH"
-	switchEnvValue := os.Getenv(switchEnvName)
-
-	return switchEnvValue == "Default Switch" || switchEnvValue == ""
+	switchName := viper.GetString(configCmd.HypervVirtualSwitch.Name)
+	return switchName == "Default Switch" || switchName == nil
```
Comment (gbraad) [inline pkg/minishift/network/settings_windows.go]: the switch should be retrieved with PowerShell, and we should compare the `ID`, since the name is localized.

**Comment by LalatenduMohanty** [comment]
@anjannath Please rebase the PR.

**Comment by anjannath** [comment]
@LalatenduMohanty Done!

File: cmd/minishift/cmd/start_preflight.go [hunk 2]
```diff
@@ -30,6 +30,7 @@ import (
 	configCmd "github.com/minishift/minishift/cmd/minishift/cmd/config"
 	"github.com/minishift/minishift/pkg/minikube/constants"
 	validations "github.com/minishift/minishift/pkg/minishift/config"
+	miniConstants "github.com/minishift/minishift/pkg/minishift/constants"
```
Comment (budhram) [inline cmd/minishift/cmd/start_preflight.go]: @anjannath , please avoid creating another alias as we already have alias dedicated for such packages.

I can give you a page explanation why it is like [`To put axe on your own foot.`](https://www.urbandictionary.com/define.php?term=To%20put%20axe%20on%20your%20own%20foot.) 😄  

See https://github.com/minishift/minishift/search?q=minishiftConstants&unscoped_q=minishiftConstants

File: pkg/minishift/network/settings_windows.go [hunk 3]
```diff
@@ -20,13 +20,14 @@ import (
...
 	"fmt"
 	"net"
-	"os"
 	"strings"
 	"time"
 
 	hvkvp "github.com/gbraad/go-hvkvp"
 	"github.com/golang/glog"
 	minishiftConfig "github.com/minishift/minishift/pkg/minishift/config"
+	"github.com/minishift/minishift/pkg/minishift/constants"
```
Comment (budhram) [inline pkg/minishift/network/settings_windows.go]: I would say stick to one format so update this as 
```
minishiftConstants "github.com/minishift/minishift/pkg/minishift/constants"
```

so that next time user will not do any error by adding another import.

Comment (gbraad) [reply pkg/minishift/network/settings_windows.go]: the problem is that we RELY on minikube constants, while we should have moved away a long time ago.

File: pkg/minishift/network/settings_windows.go [hunk 4]
```diff
@@ -41,10 +42,13 @@ var (
 )
 
 func isUsingDefaultSwitch() bool {
-	switchEnvName := "HYPERV_VIRTUAL_SWITCH"
-	switchEnvValue := os.Getenv(switchEnvName)
+	posh := powershell.New()
+	switchNameCommand := fmt.Sprintf("$swname=(Get-VM \"%s\" | Get-VMNetworkAdapter | select SwitchName).SwitchName", profile.GetActiveProfile())
```
Comment (gbraad) [inline pkg/minishift/network/settings_windows.go]: `get-vm`? This would mean this only works AFTER the vm has been created, right?

File: pkg/minishift/constants/constants.go [hunk 5]
```diff
@@ -24,18 +24,20 @@ import (
...
+	OpenshiftApiContainerName    = "k8s_apiserver_openshift-apiserver"
+	OpenshiftExec                = "/usr/bin/openshift"
+	OpenshiftOcExec              = "/usr/bin/oc"
+	DefaultProject               = "myproject"
+	DefaultUser                  = "developer"
+	DefaultUserPassword          = "developer"
+	SkipVerifyInsecureTLS        = "insecure-skip-tls-verify=true"
+	BinaryName                   = "minishift"
+	OcPathInsideVM               = "/var/lib/minishift/bin"
+	HypervDefaultVirtualSwitchId = "c08cb7b8-9b3c-408e-8e30-5e16a3aeb444"
```
Comment (gbraad) [inline pkg/minishift/constants/constants.go]: 👍

**Comment by budhram** [comment]
Functionally it seems to be working fine. I am able to start minishift VM.
```
 .\minishift.exe start --hyperv-virtual-switch "mini_s"
-- Starting profile 'minishift'
-- Check if deprecated options are used ... OK
[...]
-- Checking if Hyper-V driver is configured to use a Virtual Switch ...
   'mini_s' ... OK
-- Checking if user is a member of the Hyper-V Administrators group ... OK
-- Checking the ISO URL ... OK
[...]
-- Starting Minishift VM ............................................................................... OK
-- Checking for IP address ... OK
-- Checking for nameservers ... OK
-- Checking if external host is reachable from the Minishift VM ...
   Pinging 8.8.8.8 ... OK
-- Checking HTTP connectivity from the VM ...
   Retrieving http://minishift.io/index.html ... OK
-- Checking if persistent storage volume is mounted ... OK
-- Checking available disk space ... 1% used OK
[...]
To login as administrator:
    oc login -u system:admin
```

File: pkg/minishift/network/settings_windows.go (hunk 4 above)
Comment (anjannath) [reply pkg/minishift/network/settings_windows.go]: @gbraad Right, this function is used in the process of setting the ip address which happens after the vm has been created so, and also the name suggests, if the VM is using the default switch

File: cmd/minishift/cmd/start_preflight.go (hunk 2 above)
Comment (LalatenduMohanty) [reply cmd/minishift/cmd/start_preflight.go]: Agree with @budhram. It should be `minishiftConstants`.

Comment (LalatenduMohanty) [reply cmd/minishift/cmd/start_preflight.go]: Agree with @budhram. It should be minishiftConstants.

File: pkg/minishift/constants/constants.go (hunk 5 above)
Comment (LalatenduMohanty) [reply pkg/minishift/constants/constants.go]: 👍

File: pkg/minishift/network/settings_windows.go (hunk 3 above)
Comment (LalatenduMohanty) [reply pkg/minishift/network/settings_windows.go]: @anjannath I agree with budhram.

File: pkg/minishift/network/settings_windows.go [hunk 6]
```diff
@@ -41,10 +42,13 @@ var (
...
+	_, _, _ = posh.Execute(switchNameCommand)
```
Comment (LalatenduMohanty) [inline pkg/minishift/network/settings_windows.go]: Why are we running this i.e. `_, _, _ = posh.Execute(switchNameCommand)` as we are ignoring the output anuway? we are also running it again below `id, _, _ := posh.Execute(switchIdComman`.

Comment (gbraad) [reply pkg/minishift/network/settings_windows.go]: if using `_, _, _` you do not need the actual ignore options... :-s Just doing `posh.Execute(switchNameCommand)` would be enough

**Comment by gbraad** [comment]
@LalatenduMohanty can you describe which scenario you have tested; new instance and/or existing instance?

**Comment by amitkrout** [comment]
@anjannath What i understand is the existing function ```func isUsingDefaultSwitch() bool {``` is refactored. So user experience would be same as it was before with flag ```--hyperv-virtual-switch```. 

Correct me if i am wrong ?   If possible add a quick description of fix in the issue description area.

File: pkg/minishift/network/settings_windows.go (hunk 6 above)
Comment (anjannath) [reply pkg/minishift/network/settings_windows.go]: Okay.. i did not know that!

**Comment by anjannath** [comment]
@amitkrout No user experience changes for this PR, i have updated the first comment on how to test this and what it does.

**Comment by LalatenduMohanty** [comment]
> @LalatenduMohanty can you describe which scenario you have tested; new instance and/or existing instance?

I guess we can call it is a new setup as I had to enable HyperV first and then test the PR.

**Comment by anjannath** [comment]
Moving to WIP as the check doesnot work if a VM is not present. Will update the PR..

File: pkg/minishift/network/settings_windows.go [hunk 7]
```diff
@@ -41,10 +42,21 @@ var (
 )
 
 func isUsingDefaultSwitch() bool {
-	switchEnvName := "HYPERV_VIRTUAL_SWITCH"
-	switchEnvValue := os.Getenv(switchEnvName)
+	posh := powershell.New()
+	switchIdCommand := `(Get-VMSwitch -Name $swname).Id.Guid`
+	getSwitchIdForVmCommand := fmt.Sprintf("$swname=(Get-VM \"%s\" | Get-VMNetworkAdapter | select SwitchName).SwitchName;%s",
+		profile.GetActiveProfile(),
```
Comment (gbraad) [inline pkg/minishift/network/settings_windows.go]: We might end up jumbling arund here with the active profile. but for now, this works, although I believe this might get risky going forward...

**Comment by anjannath** [comment]
@gbraad Still facing a cyclic dependency issue, making a new package didn't solve it.
I am not able to import anything under the `cmd` namespace to the `network` package.

**Comment by anjannath** [comment]
retest this please

**Comment by anjannath** [comment]
@amitkrout Can you try the binary from this PR and check if #2638 is fixed, when you use the `Default Switch` Just pass the ip address in the same network as the ip address of the switch, it should be able to guess the correct gateway and netmask.

**Comment by amitkrout** [comment]
@anjannath thaks for the fix. Will verify the bit as directed

**Comment by anjannath** [comment]
@amitkrout Sure i'll try that tomorrow.

File: pkg/minishift/network/validations/validations.go [hunk 8]
```diff
@@ -0,0 +1,44 @@
...
+
+import (
+	"fmt"
+	"strings"
+
+	minishiftConstants "github.com/minishift/minishift/pkg/minishift/constants"
+	"github.com/minishift/minishift/pkg/minishift/shell/powershell"
+)
+
+var VMSwitch string
```
Comment (praveenkumar) [inline pkg/minishift/network/validations/validations.go]: @anjannath this doesn't make much sense, if you check your `IsUsingDefaultSwitch` implementation then it would be good to pass the switchName (whatever it will be) then evaluate it.

Comment (anjannath) [reply pkg/minishift/network/validations/validations.go]: @praveenkumar if you mean instead of using this variable just pass the value we get from `viper.GetString(configCmd.HypervVirtualSwitch.Name)` ?

File: cmd/minishift/cmd/config/config.go [hunk 9]
```diff
@@ -158,8 +158,8 @@ var (
 	DnsmasqContainerized  = createConfigSetting("network-dnsmasq-containerized", SetBool, nil, nil, true, false)
 	DnsmasqContainerImage = createConfigSetting("network-dnsmasq-container", SetString, nil, nil, true, nil)
 
-	// Hyper-V
-	HypervVirtualSwitch = createConfigSetting("hyperv-virtual-switch", SetString, []setFn{validations.IsValidHypervVirtualSwitch}, nil, true, nil)
+	// Hyper-V vSwitch set to Default Switch by default
+	HypervVirtualSwitch = createConfigSetting("hyperv-virtual-switch", SetString, []setFn{validations.IsValidHypervVirtualSwitch}, nil, true, "Default Switch")
```
Comment (gbraad) [inline cmd/minishift/cmd/config/config.go]: Right...

File: cmd/minishift/cmd/start_preflight.go [hunk 10]
```diff
@@ -410,13 +410,14 @@ func checkLibvirtDefaultNetworkActive() bool {
...
+	const defaultSwitch = "Default Switch"
 	posh := powershell.New()
 
 	switchName := viper.GetString(configCmd.HypervVirtualSwitch.Name)
 
-	// check for default switch
-	if switchName == "" {
-		checkIfDefaultSwitchExists := fmt.Sprintf("Get-VMSwitch -Id %s | ForEach-Object { $_.Name }", hypervDefaultVirtualSwitchId)
+	// check for default switch by using the Id
+	if switchName == defaultSwitch {
```
Comment (gbraad) [inline cmd/minishift/cmd/start_preflight.go]: treat as constant, like in the next line

File: pkg/minishift/constants/constants.go [hunk 11]
```diff
@@ -39,6 +39,7 @@ const (
 	OcPathInsideVM                 = "/var/lib/minishift/bin"
 	BaseDirInsideInstance          = "/var/lib/minishift/base"
 	ImageNameForClusterUpImageFlag = "openshift/origin-${component}"
+	HypervDefaultVirtualSwitchId   = "c08cb7b8-9b3c-408e-8e30-5e16a3aeb444"
```
Comment (gbraad) [inline pkg/minishift/constants/constants.go]: also add `HypervDefault...Name`

File: pkg/minishift/network/utils.go [hunk 12]
```diff
@@ -134,3 +139,41 @@ func OverrideProxyForLocalConnections(proxyAddr string) error {
...
+
+// IsUsingDefaultSwitch returns true if the Default Switch is used before creating the VM
+func IsUsingDefaultSwitch() bool {
+	posh := powershell.New()
+
+	checkIfDefaultSwitchExists := fmt.Sprintf("Get-VMSwitch -Id %s | ForEach-Object { $_.Name }", minishiftConstants.HypervDefaultVirtualSwitchId)
+	stdOut, stdErr, _ := posh.Execute(checkIfDefaultSwitchExists)
+
+	// if the config variable is epmty and default switch exists
+	if VMSwitch == "" && !strings.Contains(stdErr, "Get-VMSwitch") {
```
Comment (gbraad) [inline pkg/minishift/network/utils.go]: Maybe add something along the lines of:  `// If err contains the command, the execution failed`

File: pkg/minishift/network/utils.go [hunk 13]
```diff
@@ -134,3 +139,41 @@ func OverrideProxyForLocalConnections(proxyAddr string) error {
...
+		return true
+	}
+	return false
+}
+
+// GetVMSwitchId returns the ID of the vswitch in use by the running minishift vm on hyperv
+func GetVMSwitchId() string {
+	posh := powershell.New()
+
+	switchNameCommand := fmt.Sprintf("(Get-VMSwitch (Get-VM \"%s\" | Get-VMNetworkAdapter | select SwitchName).SwitchName).Id.Guid", profile.GetActiveProfile())
```
Comment (gbraad) [inline pkg/minishift/network/utils.go]: `switchIdCommand`

**Comment by anjannath** [comment]
@gbraad Done with the changes..
