### PR TITLE
Issue #1557 Fix openshift registry command for profiles

### LINKED ISSUE #1557: There is no openshift registry defined after running profile different than default
See https://issues.jboss.org/browse/CDK-193.

Interesting part is when there is a default profile 'minishift' exists then  'test' profile use default profile registry.
```
[budhram@dhcp35-83:~ ] $ ./minishift profile list
- minishift Running
- test    Running (active)

[budhram@dhcp35-83:~ ] $ ./minishift status
Minishift:  Running
Profile:    test
OpenShift:  Running (openshift v3.6.0+c4dd4cf)
DiskUsage:  14% of 18G

[budhram@dhcp35-83:~ ] $ ./minishift openshift registry
172.30.1.1:5000

[budhram@dhcp35-83:~ ] $ ./minishift openshift registry --profile test
172.30.1.1:5000

[budhram@dhcp35-83:~ ] $ ./minishift profile set minishift
Profile 'minishift' set as active profile

[budhram@dhcp35-83:~ ] $ ./minishift openshift registry
172.30.1.1:5000

[budhram@dhcp35-83:~ ] $ ./minishift stop
Stopping local OpenShift cluster...
Cluster stopped.

[budhram@dhcp35-83:~ ] $ ./minishift profile set test
Profile 'test' set as active profile

[budhram@dhcp35-83:~ ] $ ./minishift openshift registry
No information found for 'service/docker-registry'
```

### PR DESCRIPTION
**Pull request by budhrg**
Fix #1557 

Also fix `minishift openshift service` command whose root cause is same.

### CODE REVIEW

File: cmd/minishift/cmd/start.go [hunk 1]
```diff
@@ -171,7 +172,10 @@ func runStart(cmd *cobra.Command, args []string) {
 	// preflight checks (after start)
 	preflightChecksAfterStartingHost(hostVm.Driver)
 
-	//Adding active profile information to all instance config
+	// Persist instance kube config path to be used by other commands
+	minishiftConfig.InstanceConfig.KubeConfigPath = filepath.Join(constants.Minipath, "machines", constants.MachineName+"_kubeconfig")
```
Comment (LalatenduMohanty) [inline cmd/minishift/cmd/start.go]: Shouldn't we do this in PersistentPreRun in root.go. I do not see the value changing for each command and once set it can be reused by other commands.

Comment (budhrg) [reply cmd/minishift/cmd/start.go]: Make sense :+1:

File: cmd/minishift/cmd/root.go [hunk 2]
```diff
@@ -103,6 +103,10 @@ var RootCmd = &cobra.Command{
 			atexit.ExitWithMessage(1, fmt.Sprintf("Error creating config for VM: %s", err.Error()))
 		}
 
+		// Persist instance kube config path to be used by other commands
+		minishiftConfig.InstanceConfig.KubeConfigPath = constants.KubeConfigPath
```
Comment (LalatenduMohanty) [inline cmd/minishift/cmd/root.go]: After taking a better look, we should us `constants.KubeConfigPath` where ever `minishiftConfig.InstanceConfig.KubeConfigPath` is used currently in the PR. Both of their purpose is the same thing.  IMO `constants.KubeConfigPath` is better solution than InstanceConfig.KubeConfigPath. 
@hferentschik WDYT?

**Comment by LalatenduMohanty** [comment]
@budhrg can you please also the shorten the commit message, currently is very long. I have updated it in the github and you can reuse it.

File: cmd/minishift/cmd/root.go (hunk 2 above)
Comment (budhrg) [reply cmd/minishift/cmd/root.go]: Agree @LalatenduMohanty , same can be achieved with `constants.KubeConfigPath`. Changes done.
