### PR TITLE
Issue #1996 Check host status for console and IP command

### LINKED ISSUE #1996: Implement VM status check for each command which require VM interaction.
### General information

  * Minishift version: `v1.12.0+c12e5117`
  * OS: Linux 
  * Hypervisor: KVM 

### Steps to reproduce

  1.  Make sure that `minishift` VM is created and is in `poweroff` state.
  2.  `$ minishift console`
 
### Expected
It should display error message like `minishift VM is not running`.

### Actual
Opens up browser window with IP address of dashboard.

I'm working on a patch for this.

### PR DESCRIPTION
**Pull request by LalatenduMohanty**
Fixes #1996 

Signed-off-by: Lalatendu Mohanty <lmohanty@redhat.com>

### CODE REVIEW

File: cmd/minishift/cmd/console.go [hunk 1]
```diff
@@ -68,6 +69,13 @@ func displayConsoleInMachineReadable(hostIP string, url string) {
 }
 
 func getHostUrl(api *libmachine.Client) string {
+	vmStatus, err := cluster.GetHostStatus(api, constants.MachineName)
+	if err != nil {
+		atexit.ExitWithMessage(1, fmt.Sprintf("Error getting Minishift status: %s", err.Error()))
+	}
+	if vmStatus != machineState.Running.String() {
+		atexit.ExitWithMessage(1, "Error: Minishift is not running")
+	}
```
Comment (praveenkumar) [inline cmd/minishift/cmd/console.go]: https://github.com/minishift/minishift/issues/1996#issuecomment-366648348 we do need to do a bit extra for this.

**Comment by budhrg** [comment]
+1 for abstraction.

**Comment by amitkrout** [comment]
I think it would be nice to add post VM stop usecase in [basic feature](https://github.com/minishift/minishift/blob/master/test/integration/features/basic.feature#L171).  For example
```
Scenario: Stopping Minishift
    Given Minishift has state "Running"
     When executing "minishift stop" succeeds
     Then Minishift should have state "Stopped"

     When executing "minishift stop"
     Then Minishift should have state "Stopped"
      And stdout should contain
      """
      The 'minishift' VM is already stopped.
      """
     When executing "minishift ip”
     Then exitcode should equal "1"
     When executing "minishift console”
     Then exitcode should equal "1"
     When executing "minishift ssh”
     Then exitcode should equal "1"
```

File: cmd/minishift/cmd/console.go [hunk 2]
```diff
@@ -68,6 +69,12 @@ func displayConsoleInMachineReadable(hostIP string, url string) {
 }
 
 func getHostUrl(api *libmachine.Client) string {
+	host, err := api.Load(constants.MachineName)
+	if err != nil {
+		atexit.ExitWithMessage(1, fmt.Sprintf("Error getting Minishift status: %s", err.Error()))
+	}
+	cmdUtil.ExitIfNotRunning(host.Driver, constants.MachineName)
```
Comment (praveenkumar) [inline cmd/minishift/cmd/console.go]: 👍

File: cmd/minishift/cmd/ip.go [hunk 3]
```diff
@@ -39,6 +39,7 @@ var ipCmd = &cobra.Command{
 		if err != nil {
 			atexit.ExitWithMessage(1, fmt.Sprintf("Error getting IP: %s", err.Error()))
 		}
+		cmdUtil.ExitIfNotRunning(host.Driver, constants.MachineName)
```
Comment (praveenkumar) [inline cmd/minishift/cmd/ip.go]: 👍

File: test/integration/features/basic.feature [hunk 4]
```diff
@@ -179,6 +179,16 @@ Feature: Basic
...
       """
+    When executing "minishift console" succeeds
+     Then stdout should contain
+      """
+      Running this command requires a running 'minishift' VM, but no VM is running.
+      """
+    When executing "minishift ip" succeeds
+     Then stdout should contain
+      """
+      Running this command requires a running 'minishift' VM, but no VM is running.
```
Comment (praveenkumar) [inline test/integration/features/basic.feature]: 👍

File: test/integration/features/basic.feature [hunk 5]
```diff
@@ -179,6 +179,16 @@ Feature: Basic
       """
       The 'minishift' VM is already stopped.
       """
+    When executing "minishift console" succeeds
```
Comment (amitkrout) [inline test/integration/features/basic.feature]: +1

File: test/integration/features/basic.feature [hunk 6]
```diff
@@ -179,6 +179,16 @@ Feature: Basic
...
+     Then stdout should contain
+      """
+      Running this command requires a running 'minishift' VM, but no VM is running.
+      """
+    When executing "minishift ip" succeeds
```
Comment (amitkrout) [inline test/integration/features/basic.feature]: +1

File: test/integration/features/basic.feature (hunk 5 above)
Comment (LalatenduMohanty) [reply test/integration/features/basic.feature]: @amitkrout That's because we are returning exit code zero as it is exactly not a failure but a graceful exit.

Comment (amitkrout) [reply test/integration/features/basic.feature]: Then its fine, thanks for the clarification

Comment (budhrg) [reply test/integration/features/basic.feature]: screenshot from 2018-02-28 19-05-46
