### PR TITLE
Issue #3082 Using a working GPG key for RVM

### LINKED ISSUE #3082: Jobs in ci.centos.org/job/minishift-docs is failing
Jobs in https://ci.centos.org/job/minishift-docs/63/consoleFull failing as it seems gpg key for RVM has changed. 

Here is the code responsible for failure https://github.com/minishift/minishift/blob/master/centos_ci.sh#L165-L166

```
# gpg2 --keyserver hkp://keys.gnupg.net --recv-keys D39DC0E3
gpg: directory `/root/.gnupg' created
gpg: new configuration file `/root/.gnupg/gpg.conf' created
gpg: WARNING: options in `/root/.gnupg/gpg.conf' are not yet active during this run
gpg: keyring `/root/.gnupg/secring.gpg' created
gpg: keyring `/root/.gnupg/pubring.gpg' created
gpg: requesting key D39DC0E3 from hkp server keys.gnupg.net
gpg: /root/.gnupg/trustdb.gpg: trustdb created
gpg: key D39DC0E3: public key "Michal Papis (RVM signing) <mpapis@gmail.com>" imported
gpg: key D39DC0E3: public key "Totally Legit Signing Key <mallory@example.org>" imported
gpg: no ultimately trusted keys found
gpg: Total number processed: 2
gpg:               imported: 2  (RSA: 2)

#  curl -L get.rvm.io | bash -s stable
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   194  100   194    0     0    272      0 --:--:-- --:--:-- --:--:--   272
100 24593  100 24593    0     0  26613      0 --:--:-- --:--:-- --:--:-- 26613
Downloading https://github.com/rvm/rvm/archive/1.29.6.tar.gz
Downloading https://github.com/rvm/rvm/releases/download/1.29.6/1.29.6.tar.gz.asc
gpg: Signature made Thursday 13 December 2018 03:09:53 PM UTC using RSA key ID 39499BDB
gpg: Can't check signature: No public key
Warning, RVM 1.26.0 introduces signed releases and automated check of signatures when GPG software found. Assuming you trust Michal Papis import the mpapis public key (downloading the signatures).

GPG signature verification failed for '/usr/local/rvm/archives/rvm-1.29.6.tgz' - 'https://github.com/rvm/rvm/releases/download/1.29.6/1.29.6.tar.gz.asc'! Try to install GPG v2 and then fetch the public key:

    gpg2 --keyserver hkp://keys.gnupg.net --recv-keys 409B6B1796C275462A1703113804BB82D39DC0E3 7D2BAF1CF37B13E2069D6956105BD0E739499BDB

or if it fails:

    command curl -sSL https://rvm.io/mpapis.asc | gpg2 --import -
    command curl -sSL https://rvm.io/pkuczynski.asc | gpg2 --import -

the key can be compared with:

    https://rvm.io/mpapis.asc or https://keybase.io/mpapis
    https://rvm.io/pkuczynski.asc

NOTE: GPG version 2.1.17 have a bug which cause failures during fetching keys from remote server. Please downgrade or upgrade to newer version (if available) or use the second method described above.

```
Refer : https://ci.centos.org/job/minishift-docs/63/consoleFull

### PR DESCRIPTION
**Pull request by LalatenduMohanty**
Signed-off-by: Lalatendu Mohanty <lmohanty@redhat.com>

Fixes #3082

### CODE REVIEW

**Comment by LalatenduMohanty** [comment]
https://ci.centos.org/job/minishift-docs/64/ does not use the PR as the PR needs to be merged to first.

File: centos_ci.sh [hunk 1]
```diff
@@ -162,7 +162,7 @@ function install_docs_prerequisite_packages() {
                      java-1.7.0-openjdk-devel
 
   # Install RVM
-  gpg2 --keyserver hkp://keys.gnupg.net --recv-keys D39DC0E3
+  gpg2 --keyserver hkp://keys.gnupg.net --recv-keys 409B6B1796C275462A1703113804BB82D39DC0E3 7D2BAF1CF37B13E2069D6956105BD0E739499BDB
```
Comment (praveenkumar) [inline centos_ci.sh]: :+1:
