### PR TITLE
Issue #2056 Check writable permission before downloading during update

### LINKED ISSUE #2056: 'minishift update' should check write permissions before downloading
### General information

  * Minishift version: 1.12.0
  * OS: Linux
  * Hypervisor: KVM

### Steps to reproduce

  1. Run `minishift update`

### Expected
`minishift update` should check if it has write permissions to the target directory for installation before downloading the latest release, not after. Once this fails, I need to run `sudo minishift update` again which again downloads the binary. This is a bit painful because downloads from GitHub are generally slow.

### Actual
```console
$ minishift update
A newer version of minishift is available.
Do you want to update from 1.12.0 to 1.13.1 now? [y/N]: y
Downloading https://github.com/minishift/minishift/releases/download/v1.13.1/minishift-1.13.1-linux-amd64.tgz
 5.19 MiB / 5.19 MiB [=============================================================================================] 100.00% 0s
 65 B / 65 B [=====================================================================================================] 100.00% 0s
Update failed: open /usr/local/bin/.minishift.new: permission denied
```

### PR DESCRIPTION
**Pull request by budhrg**
Fix #2056 

Need to test in mac and Windows.

### CODE REVIEW

File: pkg/util/utils.go [hunk 1]
```diff
@@ -178,3 +179,17 @@ func CommandExecutesSuccessfully(cmd string, args ...string) bool {
 	}
 	return false
 }
+
+// IsDirectoryWritable checks if the directory is writable or not
+// by trying creating a temporary file
+// Return true if directory is writable else false
+func IsDirectoryWritable(path string) bool {
```
Comment (budhrg) [inline pkg/util/utils.go]: Couldn't find a direct logic hence using it. Let me know if have good solution.

Comment (anjannath) [reply pkg/util/utils.go]: I think this is good, it finds out the truth if the directory is actually wirtable or not.
I was thinking about using `Stat()` and get the `Mode().Perm()` but this will only work in unix like systems.
> IsReadable and IsWritable wouldn't be reliable enough... the filesystem can be mounted read-only, or corrupt, or there could be extended attribute ACLs on the file, etc.  The only reliable strategy is to just try to open it for read or write and see if it fails.


Found this mail threaed on the golang-dev mailing list abou it: https://groups.google.com/forum/#!msg/golang-dev/qfenPFNYdYY/8tkDvE3KaUQJ

Comment (budhrg) [reply pkg/util/utils.go]: If `Brad Fitzpatrick` is saying then I am sure it is one of good approach :)

File: pkg/minishift/update/update.go [hunk 2]
```diff
@@ -78,6 +80,11 @@ func IsNewerVersion(localVersion, latestVersion semver.Version) bool {
 func Update(latestVersion semver.Version) error {
 	var extName string
 
+	path, _ := osext.Executable()
+	if writable := util.IsDirectoryWritable(path); !writable {
+		return fmt.Errorf("Directory '%s' containing binary doesn't have write permission.\nPlease fix the permission issue and try running the command again.", filepath.Dir(path))
+	}
```
Comment (LalatenduMohanty) [inline pkg/minishift/update/update.go]: s/containing binary// i.e. `Directory '%s' doesn't have write permission.\nPlease fix the permission issue and try running the command again.`

Comment (budhrg) [reply pkg/minishift/update/update.go]: Sure

Comment (budhrg) [reply pkg/minishift/update/update.go]: Done

**Comment by LalatenduMohanty** [comment]
@budhrg looks like the appveyor test failed without any reason can you do another force push to see if we can reproduce the issue. 
```
-- PASS: TestSplitAndTrim (0.00s)
760
PASS
761
ok  	github.com/minishift/minishift/pkg/util/strings	0.093s
762
?   	github.com/minishift/minishift/pkg/version	[no test files]
763
make: *** [test] Error 1
764
Command exited with code 2
```

File: pkg/util/utils_test.go [hunk 3]
```diff
@@ -206,3 +207,24 @@ func Test_command_executes_unsuccessfully_with_command_lookup(t *testing.T) {
...
+	assert.True(t, IsDirectoryWritable(fmt.Sprintf("%s/foo", testDir)))
+}
+
+func TestNonWritableDirectory(t *testing.T) {
+	testDir, err := ioutil.TempDir("", "minishift-test-")
+	assert.NoError(t, err)
+	defer os.RemoveAll(testDir)
+
+	if runtime.GOOS == "windows" {
+		testDir = "C:/Windows/System" // using some known non-writable directory
```
Comment (budhrg) [inline pkg/util/utils_test.go]: `os.Chmod` is not working in Windows.

File: pkg/util/utils.go [hunk 4]
```diff
@@ -178,3 +180,17 @@ func CommandExecutesSuccessfully(cmd string, args ...string) bool {
...
+	tmpFilePath := filepath.Join(path, "tmp")
+	_, err := os.Create(tmpFilePath)
+	defer os.Remove(tmpFilePath)
```
Comment (containscafeine) [inline pkg/util/utils.go]: `defer` statement should be called after the error is checked
