### PR TITLE
Issue #1277 and #1339 Add no progress bar flag and fix spinning wheel

### LINKED ISSUE #1277: Add a flag for non-interactive shells or detect them automatically
When you launch minishift/cdk from Eclipse, it uses the Console view to show the output.
At the beginning there is this spinning thing showing progress. Unfortunately it doesn't behave well in the non-interactive console view:
```
Starting local OpenShift cluster using 'virtualbox' hypervisor...
--
Registering machine using subscription-manager
[37m\|[0m   [37m/[0m   [37m-[0m   [37m\[0m   [37m\|[0m   [37m/[0m   [37m-[0m   [37m\[0m
```

See more details at https://issues.jboss.org/browse/JBIDE-24676 .

Rob suggested that we need a flag to turn this off. Another option would be to detect the shell automatically and output something non-changing in a non-interactive shell.

### PR DESCRIPTION
**Pull request by budhrg**
Fix #1277  and #1339 .

```
$ minishift start
-- Installing default add-ons ... OK
[...]

   Downloading ISO 'https://github.com/minishift/minishift-b2d-iso/releases/download/v1.1.0/minishift-b2d.iso'
 40.00 MiB / 40.00 MiB [==========================================================================================================================================================] 100.00% 0s
-- Starting Minishift VM ... OK
[...]
-- Downloading OpenShift binary 'oc' version 'v3.6.0'
 12.04 MiB / 34.72 MiB [=====================================================>---------------------------------------------------------------------------------------------------]  34.69% 24s^C



$ MINISHIFT_NO_PROGRESSBAR=y minishift start
-- Installing default add-ons ... OK
[...]
   Downloading ISO 'https://github.com/minishift/minishift-b2d-iso/releases/download/v1.1.0/minishift-b2d.iso'
-- Starting Minishift VM ... OK
[...]
-- Downloading OpenShift binary 'oc' version 'v3.6.0'
-- OpenShift cluster will be configured with ...



$ minishift start --iso-url file:///home/budhram/cache/iso/minishift-rhel7.iso --username $USER --password $PASS
-- Checking if KVM driver is installed ... 
   Driver is available at /usr/local/bin/docker-machine-driver-kvm ... OK
-- Starting local OpenShift cluster using 'kvm' hypervisor ...
-- Minishift VM will be configured with ...
   Memory:    2 GB
   vCPUs :    2
   Disk size: 20 GB
-- Starting Minishift VM ... OK
Registering machine using subscription-manager
[...]
-- Downloading OpenShift binary 'oc' version 'v3.6.0'
 798.53 KiB / 34.72 MiB [===>---------------------------------------------------------------------------------------------------------------------------------------------------]   2.25% 7m7s


$ MINISHIFT_NO_PROGRESSBAR=y minishift start --iso-url file:///home/budhram/cache/iso/minishift-rhel7.iso --username $USER --password $PASS
-- Checking if KVM driver is installed ... 
[...]
-- Starting Minishift VM ... OK
Registering machine using subscription-manager
Registration successful 40.6s
-- Checking for IP address ... OK
-- Checking if external host is reachable from the Minishift VM ... 
   Pinging 8.8.8.8 ... OK
-- Checking HTTP connectivity from the VM ... 
   Retrieving http://minishift.io/index.html ... OK
-- Checking if persistent storage volume is mounted ... OK
-- Checking available disk space ... 1% OK
-- Downloading OpenShift binary 'oc' version 'v3.6.0'
-- OpenShift cluster will be configured with ...
...
```

### CODE REVIEW

File: pkg/minishift/registration/registration.go [hunk 1]
```diff
@@ -36,10 +36,6 @@ type Detector interface {
 
 type StandardRegistrator struct{}
 
-func SetDetector(newDetector Detector) {
```
Comment (budhrg) [inline pkg/minishift/registration/registration.go]: Unused code.

File: pkg/minishift/registration/utils.go [hunk 2]
```diff
@@ -31,13 +31,6 @@ type RegistrationParameters struct {
 	GetPasswordInteractive func(message string) string
 }
 
-// Detect supported Registrator
-func NeedRegistration(host *host.Host) (bool, error) {
```
Comment (budhrg) [inline pkg/minishift/registration/utils.go]: Unused code.

**Comment by gbraad** [comment]
I will hold off for a short moment to merge this.

Want feedback on the spinner library and see if this can be fixed in a different way.
Adding a flag or feature is easy, but it will be difficult to remove this.

Also, has the OP responded to the suggestion of using an environment variable... will this work for them?

File: pkg/minishift/provisioner/minishift_provisioner.go [hunk 3]
```diff
@@ -111,12 +111,12 @@ func (provisioner *MinishiftProvisioner) Provision(swarmOptions swarm.Options, a
 	}
 	provisioner.EngineOptions.StorageDriver = storageDriver
 
-	fmt.Printf("\n   Setting hostname ... ")
+	log.Info("\n   Setting hostname ... ")
```
Comment (gbraad) [inline pkg/minishift/provisioner/minishift_provisioner.go]: This is not part of the same issue

File: pkg/minishift/registration/redhat.go [hunk 4]
```diff
@@ -63,8 +64,12 @@ func (registrator *RedHatRegistrator) CompatibleWithDistribution(osReleaseInfo *
 
 // Register attempts to register the system with RHSM
 func (registrator *RedHatRegistrator) Register(param *RegistrationParameters) error {
+	var spinnerView *spinner.Spinner
+
 	if isRegistered, err := registrator.isRegistered(); !isRegistered && err == nil {
-		spinnerView := spinner.New(spinner.CharSets[9], SPINNER_SPEED*time.Millisecond)
+		if !cmdUtil.HasEnabledNoProgressbar {
```
Comment (gbraad) [inline pkg/minishift/registration/redhat.go]: I believe we should use `ShowProgressbars` (default `true`) and allow the `ProcessEnvironmentVariables` function to toggle this off. This sentence has a double negation... :-s

File: pkg/minishift/registration/redhat.go [hunk 5]
```diff
@@ -87,11 +92,15 @@ func (registrator *RedHatRegistrator) Register(param *RegistrationParameters) er
 				param.Username,
 				minishiftStrings.EscapeSingleQuote(param.Password))
 
-			// start timed SSH command to register
-			spinnerView.Start()
+			if spinnerView != nil {
```
Comment (gbraad) [inline pkg/minishift/registration/redhat.go]: and if done so, we do not check for `if spinnerView != nil`, but only need to concern about `if ShowProgressBars { ... }`

File: pkg/minishift/registration/utils.go [hunk 6]
```diff
@@ -47,7 +40,7 @@ func doRegistrationHostAction(actionMessage string, registrationAction Registrat
 		return false, err
 	}
 
-	// was succesfully
+	// was successfully
```
Comment (gbraad) [inline pkg/minishift/registration/utils.go]: if you change it, please correct it to `was successful` (no adjective form, as I actually forgot to add `completed`)

File: pkg/util/github/github.go [hunk 7]
```diff
@@ -133,7 +134,7 @@ func DownloadOpenShiftReleaseBinary(binaryType OpenShiftBinaryType, osType minis
 		defer func() { _ = httpResp.Body.Close() }()
 
 		asset = httpResp.Body
-		if httpResp.ContentLength > 0 {
+		if !util.HasEnabledNoProgressbar && httpResp.ContentLength > 0 {
```
Comment (gbraad) [inline pkg/util/github/github.go]: if `ShowProgressBars &&`

File: pkg/minishift/registration/registration.go (hunk 1 above)
Comment (gbraad) [inline pkg/minishift/registration/registration.go]: Create an issue for removing the code and create a separate commit for this...

File: pkg/minishift/registration/utils.go (hunk 2 above)
Comment (gbraad) [reply pkg/minishift/registration/utils.go]: ditto... not part of this commit

File: cmd/minishift/cmd/root.go [hunk 8]
```diff
@@ -166,13 +166,22 @@ func setFlagsUsingViper() {
...
 	if err == util.BooleanFormatError {
 		atexit.ExitWithMessage(1, fmt.Sprintf("Error enabling experimental features: %s", err))
 	}
 	hasEnabledExperimental = enableExperimental
 
+	noProgressbar, err := util.GetBoolEnv(util.EnableNoProgressbarEnv)
+	if err == util.BooleanFormatError {
+		atexit.ExitWithMessage(1, fmt.Sprintf("Error enabling no progress bar action: %s", err))
+	}
+	util.HasEnabledNoProgressbar = noProgressbar
```
Comment (gbraad) [inline cmd/minishift/cmd/root.go]: `ShowProgressBars = !enableNoProgressBars`

Not sure if `util` is the correct place for this boolean. Sounds more like `config`

**Comment by gbraad** [comment]
I will hold off for a short moment to merge this.

Want feedback on the spinner library and see if this can be fixed in a different way.
Adding a flag or feature is easy, but it will be difficult to remove this.

Also, has the OP responded to the suggestion of using an environment variable... will this work for them?

File: pkg/minishift/registration/redhat.go (hunk 4 above)
Comment (budhrg) [reply pkg/minishift/registration/redhat.go]: Ack

**Comment by budhrg** [comment]
> Also, has the OP responded to the suggestion of using an environment variable... will this work for them?

**Comment by gbraad** [comment]
In the library colorization is used (forced to use white), and this is written to the output with https://github.com/briandowns/spinner/blob/master/spinner.go#L108. I believe Eclipse just does not handle ANSI codes (as used for colorization) correctly.

Can you test if turning off the colorization will work? If so, this can be a fix to the upstream library in which this can be turned off. Maybe by modifying this line first?

**Comment by gbraad** [comment]
We can use an alternative strategy.

We use our own Charset: https://github.com/briandowns/spinner/blob/master/character_sets.go with only `{".", " "}` which then will print a blinking dot. but on the Eclipse console becomes a spaced dot indicating the progress? it is worth a shot. WDYT?

**Comment by gbraad** [comment]
```
package main

import (
        "github.com/briandowns/spinner"
        "time"
)

func main() {
        s := spinner.New([]string{".", " "}, time.Second)
        s.Start() 
        time.Sleep(30 * time.Second)
        s.Stop()
}
```

**Comment by budhrg** [comment]
> We use our own Charset: https://github.com/briandowns/spinner/blob/master/character_sets.go with only {".", " "} which then will print a blinking dot. but on the Eclipse console becomes a spaced dot indicating the progress? it is worth a shot. WDYT?

@gbraad checking this behavior eclipse/devstudio.

**Comment by gbraad** [comment]
On both Linux and Windows. At the moment I can not test it... but it looked
'OK-ish' here...

File: pkg/minishift/provisioner/minishift_provisioner.go (hunk 3 above)
Comment (budhrg) [reply pkg/minishift/provisioner/minishift_provisioner.go]: @gbraad , getting some spinning wheel issue on print it here. See https://github.com/minishift/minishift/issues/1339

**Comment by budhrg** [comment]
Now, the logs are shown as : 
```
$ minishift start --username bgurung@redhat.com --password '*****' --iso-url file:///home/budhram/cache/iso/minishift-rhel7.iso
-- Checking if KVM driver is installed ... 
   Driver is available at /usr/local/bin/docker-machine-driver-kvm ... 
   Checking driver binary is executable ... OK
-- Starting local OpenShift cluster using 'kvm' hypervisor ...
-- Minishift VM will be configured with ...
   Memory:    2 GB
   vCPUs :    2
   Disk size: 20 GB
-- Starting Minishift VM ............ OK
-- Registering machine using subscription-manager ............... OK [1m0s]
-- Checking for IP address ... OK
-- Checking if external host is reachable from the Minishift VM ... 
   Pinging 8.8.8.8 ... OK
-- Checking HTTP connectivity from the VM ... 
   Retrieving http://minishift.io/index.html ... OK
-- Checking if persistent storage volume is mounted ... OK
-- Checking available disk space ... 1% OK
-- OpenShift cluster will be configured with ...
   Version: v3.6.0
-- Checking `oc` support for startup flags ... 
   routing-suffix ... OK
   host-config-dir ... OK
   host-data-dir ... OK
   host-pv-dir ... OK
   host-volumes-dir ... OK
Starting OpenShift using openshift/origin:v3.6.0 ...
Pulling image openshift/origin:v3.6.0
[...]
```

**Comment by gbraad** [comment]
This is VERY acceptable...

File: cmd/minishift/cmd/util/util.go [hunk 9]
```diff
@@ -71,3 +72,17 @@ func UnpackAddons(addonsDir string) error {
 
 	return nil
 }
+
+func ShowProgressDots(progressDots chan bool) {
```
Comment (gbraad) [inline cmd/minishift/cmd/util/util.go]: +1

File: pkg/minishift/provisioner/minishift_provisioner.go (hunk 3 above)
Comment (gbraad) [reply pkg/minishift/provisioner/minishift_provisioner.go]: This is not how it was originally printed. The OK was not on the informative line about setting the hostname.

File: cmd/minishift/cmd/start.go [hunk 10]
```diff
@@ -22,10 +22,8 @@ import (
 	"strings"
 
 	"os"
-	"time"
 
 	"github.com/asaskevich/govalidator"
-	"github.com/briandowns/spinner"
```
Comment (gbraad) [inline cmd/minishift/cmd/start.go]: remove from glide.yaml and glide.lock

File: glide.lock [hunk 11]
```diff
@@ -1,13 +1,10 @@
-hash: 8a468283a9a4675c087c7d25a00ce4a72c4fc0f5f05abe60eec93bfce22be14b
-updated: 2017-07-10T11:56:37.047777606+02:00
+hash: 675036c36eaf7c64def2072063154d6e2f3d670a2c09c4396db9b2359b83bdcc
+updated: 2017-09-04T20:16:55.757240937+05:30
 imports:
 - name: github.com/asaskevich/govalidator
   version: 7b3beb6df3c42abd3509abfc3bcacc0fbfb7c877
 - name: github.com/blang/semver
   version: b38d23b8782a487059e8fc8773e9a5b228a77cb6
-- name: github.com/briandowns/spinner
```
Comment (gbraad) [inline glide.lock]: OK

File: pkg/minishift/registration/utils.go [hunk 12]
```diff
@@ -93,7 +93,7 @@ func UnregisterHostVM(host *host.Host, param *RegistrationParameters) (bool, err
 	}
 
 	return doRegistrationHostAction(
-		"Unregistering machine",
+		"Unregistering machine\n",
```
Comment (gbraad) [inline pkg/minishift/registration/utils.go]: isn't this needed for all the registration host actions? if soo, make that a println

File: pkg/minishift/registration/utils.go [hunk 13]
```diff
@@ -41,13 +41,13 @@ func NeedRegistration(host *host.Host) (bool, error) {
 type RegistrationHostActionFunc func(param *RegistrationParameters) error
 
 func doRegistrationHostAction(actionMessage string, registrationAction RegistrationHostActionFunc, param *RegistrationParameters) (bool, error) {
-	fmt.Println(actionMessage)
+	fmt.Print(actionMessage)
```
Comment (gbraad) [inline pkg/minishift/registration/utils.go]: ????? and later you add a `\n` ?

File: pkg/minishift/registration/utils.go [hunk 14]
```diff
@@ -71,7 +71,7 @@ func RegisterHostVM(host *host.Host, param *RegistrationParameters) (bool, error
 	}
 
 	return doRegistrationHostAction(
-		"Registering machine using subscription-manager",
+		"-- Registering machine using subscription-manager ...",
```
Comment (gbraad) [inline pkg/minishift/registration/utils.go]: because of the progress dots?

File: pkg/minishift/registration/utils.go (hunk 13 above)
Comment (gbraad) [reply pkg/minishift/registration/utils.go]: I see...

File: pkg/minishift/registration/utils.go (hunk 14 above)
Comment (gbraad) [reply pkg/minishift/registration/utils.go]: Maybe this should be on a new line anyways, with an indicative message.

because when I need to specify the username and password interactively, how is it shown now?

File: cmd/minishift/cmd/util/util.go [hunk 15]
```diff
@@ -71,3 +72,17 @@ func UnpackAddons(addonsDir string) error {
...
+	go func() {
+		for {
+			select {
+			case <-progressDots:
+				return
+			default:
+				fmt.Print(".")
+				time.Sleep(5 * time.Second)
```
Comment (gbraad) [inline cmd/minishift/cmd/util/util.go]: Maybe configurable... 5 seconds between a dot is quite long. 

The general human response time to think something is acted on is about 300ms. So, printing needs to happen fast before it starts a long process... but it is possible to take about 3 seconds before the brain needs another stimulus. 5 stretches it... so in the case of the registration it might need more ? but for starting the VM it can be faster...

WDYT? what gave the best results?

File: pkg/util/utils.go [hunk 16]
```diff
@@ -137,7 +137,7 @@ func TimeElapsed(start time.Time, friendly bool) string {
 		elapsed = FriendlyDuration(elapsed)
 	}
 
-	return elapsed.String()
+	return fmt.Sprintf("[%v]", elapsed.String())
```
Comment (gbraad) [inline pkg/util/utils.go]: Why the brackets?

File: pkg/minishift/registration/redhat.go [hunk 17]
```diff
@@ -87,15 +86,16 @@ func (registrator *RedHatRegistrator) Register(param *RegistrationParameters) er
...
+			// stops the progress of dots
+			progressDots <- true
 			if err == nil {
-				fmt.Print("Registration successful ")
+				fmt.Print(" OK ")
 			} else {
-				fmt.Print("Registration unsuccessful ")
+				fmt.Print(" FAIL ")
 			}
 			fmt.Println(util.TimeElapsed(startTime, true))
```
Comment (gbraad) [inline pkg/minishift/registration/redhat.go]: If you want brackets, you would have to put them here...

The function https://github.com/budhrg/minishift/blob/03606c244dcf5030a2e0c2d357d7f0f888fb2c59/pkg/util/utils.go#L133 is a util function, and would need to produce a result that can be processed easily without side-effects or markup.

File: pkg/util/utils.go (hunk 16 above)
Comment (gbraad) [inline pkg/util/utils.go]: Brackets should not be added here... but where the output is used:
https://github.com/budhrg/minishift/blob/03606c244dcf5030a2e0c2d357d7f0f888fb2c59/pkg/minishift/registration/redhat.go#L100

File: pkg/minishift/registration/redhat.go (hunk 17 above)
Comment (budhrg) [reply pkg/minishift/registration/redhat.go]: Sure

File: cmd/minishift/cmd/util/util.go (hunk 15 above)
Comment (budhrg) [reply cmd/minishift/cmd/util/util.go]: 3 seconds looks good. Configurable make sense. For registration, it takes long so will keep three and for starting VM 2 second probably.

**Comment by budhrg** [comment]
@gbraad , @LalatenduMohanty , I updated the PR make interactive and non-active registration consistent

```
#----------- Non-Interactive Registration
-- Starting Minishift VM ........................ OK
Registering machine using subscription-manager
Red Hat Developers or Red Hat Subscription Management (RHSM) username: bgurung@redhat.com
Red Hat Developers or Red Hat Subscription Management (RHSM) password: [HIDDEN]
...............
Registration successful [30s]


#----------- Interactive Registration

-- Starting Minishift VM ........................ OK
Registering machine using subscription-manager
................
Registration successful [32s]

```

File: pkg/minishift/registration/utils.go (hunk 14 above)
Comment (budhrg) [reply pkg/minishift/registration/utils.go]: @gbraad , Updated the PR now. It was not looking intutive :)

```
-- Registering machine using subscription-manager ...Red Hat Developers or Red Hat Subscription Management (RHSM) username: bgurung@redhat.com
Red Hat Developers or Red Hat Subscription Management (RHSM) password: [HIDDEN]
........... OK [33s]
```

File: cmd/minishift/cmd/root.go [hunk 18]
```diff
@@ -70,7 +70,7 @@ var viperWhiteList = []string{
 	"log_dir",
 }
 
-var hasEnabledExperimental bool = false
+var hasEnabledExperimental bool
```
Comment (LalatenduMohanty) [inline cmd/minishift/cmd/root.go]: 👍

**Comment by gbraad** [comment]
@budhrg maybe indicating what is happening as follows?
```
Registering machine using subscription-manager
Awaiting response ................ OK [32s]
```

File: cmd/minishift/cmd/util/util.go [hunk 19]
```diff
@@ -71,3 +72,17 @@ func UnpackAddons(addonsDir string) error {
...
+
+func ShowProgressDots(progressDots chan bool) {
+	go func() {
+		for {
+			select {
+			case <-progressDots:
+				return
+			default:
+				fmt.Print(".")
+				time.Sleep(2 * time.Second)
```
Comment (LalatenduMohanty) [inline cmd/minishift/cmd/util/util.go]: I think we should use 1 second instead of 2 seconds. While testing it I felt the dots were little slow.

File: cmd/minishift/cmd/util/util.go (hunk 9 above)
Comment (LalatenduMohanty) [reply cmd/minishift/cmd/util/util.go]: I think we should name it `StartProgressDots`.

Comment (LalatenduMohanty) [reply cmd/minishift/cmd/util/util.go]: Also I think we should move this function to minishift pkg/Util.

File: cmd/minishift/cmd/start.go [hunk 20]
```diff
@@ -349,9 +345,10 @@ func startHost(libMachineClient *libmachine.Client) *host.Host {
 	if err != nil {
 		atexit.ExitWithMessage(1, fmt.Sprintf("Error starting the VM: %v", err))
 	}
-	spinnerView.Stop()
-	fmt.Println("OK")
+	// Stops the progress of dots
+	progressDots <- true
```
Comment (LalatenduMohanty) [inline cmd/minishift/cmd/start.go]: `progressDots <- true` should be in a function. Even if it is just one line a function would help to encapsulate it and if we want to change or add more to it in the future it would be easy.

File: cmd/minishift/cmd/util/util.go (hunk 19 above)
Comment (LalatenduMohanty) [reply cmd/minishift/cmd/util/util.go]: Tested the updated code and 2 seconds seems fine now.

File: cmd/minishift/cmd/start.go (hunk 20 above)
Comment (gbraad) [reply cmd/minishift/cmd/start.go]: Agree... abstract it.

Maybe even as a package for just the progress dots, so it reads as
```
progress.Start()
...
proogress.Stop()
```

**Comment by budhrg** [comment]
@LalatenduMohanty , @gbraad , Updated as per our discussion

```
#------------------- Non-Interactive Registration -----------
$ minishift start --username bgurung@redhat.com --password '****' --iso-url file:///home/budhram/cache/iso/minishift-rhel7.iso
-- Checking if KVM driver is installed ... 
   Driver is available at /usr/local/bin/docker-machine-driver-kvm ... 
   Checking driver binary is executable ... OK
-- Starting local OpenShift cluster using 'kvm' hypervisor ...
-- Minishift VM will be configured with ...
   Memory:    2 GB
   vCPUs :    2
   Disk size: 20 GB
-- Starting Minishift VM ....................... OK
Registering machine using subscription-manager 
Registration in progress ............... OK [30s]
[...]


#------------------- Interactive Registration -----------

$ minishift start --iso-url file:///home/budhram/cache/iso/minishift-rhel7.iso
-- Checking if KVM driver is installed ... 
   Driver is available at /usr/local/bin/docker-machine-driver-kvm ... 
   Checking driver binary is executable ... OK
-- Starting local OpenShift cluster using 'kvm' hypervisor ...
-- Minishift VM will be configured with ...
   Memory:    2 GB
   vCPUs :    2
   Disk size: 20 GB
-- Starting Minishift VM ....................... OK
Registering machine using subscription-manager 
Red Hat Developers or Red Hat Subscription Management (RHSM) username: bgurung@redhat.com
Red Hat Developers or Red Hat Subscription Management (RHSM) password: [HIDDEN]
Registration in progress ................. OK [34s]
[...]
```

File: pkg/minishift/provisioner/minishift_provisioner.go (hunk 3 above)
Comment (budhrg) [reply pkg/minishift/provisioner/minishift_provisioner.go]: @LalatenduMohanty , WDYT about this change? Right now if we print this, it is altering the expected progress dots behavior. See above comment.

**Comment by budhrg** [comment]
@LalatenduMohanty , 

> We should fix the alignment of "Invalid username or password. Retry:

Fixed now

```
-- Starting Minishift VM ......................... OK
-- Registering machine using subscription-manager 
   Red Hat Developers or Red Hat Subscription Management (RHSM) username: basfd
   Red Hat Developers or Red Hat Subscription Management (RHSM) password: [HIDDEN]
   Registration in progress .. FAIL [4s]
   Invalid username or password. Retry: 1
   Red Hat Developers or Red Hat Subscription Management (RHSM) username: bgurung@redhat.com
   Red Hat Developers or Red Hat Subscription Management (RHSM) password: [HIDDEN]
   Registration in progress ............... OK [30s]
-- Checking for IP address ... OK
....
```

File: pkg/minishift/provisioner/minishift_provisioner.go (hunk 3 above)
Comment (LalatenduMohanty) [reply pkg/minishift/provisioner/minishift_provisioner.go]: I am ok with using `glog.V(2).Infof` or log.Info as we need to fix it anyway with #169 .

Comment (budhrg) [reply pkg/minishift/provisioner/minishift_provisioner.go]: With `log.Info`, this message will appear in `--show-libmachine-logs` flag enabled as well. Hence, I am in favor of it.

File: pkg/minishift/registration/redhat.go [hunk 21]
```diff
@@ -63,9 +61,9 @@ func (registrator *RedHatRegistrator) CompatibleWithDistribution(osReleaseInfo *
 
 // Register attempts to register the system with RHSM
 func (registrator *RedHatRegistrator) Register(param *RegistrationParameters) error {
-	if isRegistered, err := registrator.isRegistered(); !isRegistered && err == nil {
-		spinnerView := spinner.New(spinner.CharSets[9], SPINNER_SPEED*time.Millisecond)
+	progressDots := make(chan bool)
```
Comment (gbraad) [inline pkg/minishift/registration/redhat.go]: This should have been in a function too...

File: cmd/minishift/cmd/start.go [hunk 22]
```diff
@@ -302,7 +297,7 @@ func determineInsecureRegistry(key string) []string {
 }
 
 func startHost(libMachineClient *libmachine.Client) *host.Host {
-	spinnerView := spinner.New(spinner.CharSets[9], SPINNER_SPEED*time.Millisecond)
+	progressDots := make(chan bool)
```
Comment (gbraad) [inline cmd/minishift/cmd/start.go]: should be abstracted
