### PR TITLE
Issue #2318 Fix preflight check for extra-clusterup-flags

### LINKED ISSUE #2318: Regression with --extra-clusterup-flags
With https://github.com/minishift/minishift/commit/850813734dcf6482486cb7397789dd888844988a the flags support check for `oc` got moved to the pre-flight, but we miss an essential part:

https://github.com/minishift/minishift/blob/850813734dcf6482486cb7397789dd888844988a/pkg/minishift/clusterup/clusterup.go#L72-L77

This strips the `--extra-clusterup-flags` from being passed to the `oc cluster up` support check. After the check, the flags get passed in for execution:

https://github.com/minishift/minishift/blob/850813734dcf6482486cb7397789dd888844988a/pkg/minishift/clusterup/clusterup.go#L89-L92

Without this `delete`, the following error occurs:

```
-- Checking if provided oc flags are supported ... Flag 'extra-clusterup-flags' is not supported for oc version v3.9.0. Use 'openshift-version' flag to select a different version of OpenShift.
FAIL
Provided oc flag not supported
```

For more info, see: https://gist.github.com/cmoulliard/039e85e17ee99ad8c9e25b975d3f3a8a#gistcomment-2561177

### PR DESCRIPTION
**Pull request by LalatenduMohanty**
Fixes #2318 

Signed-off-by: Lalatendu Mohanty <lmohanty@redhat.com>

Here is the step to test this PR:

Without this PR
```
$ minishift start --extra-clusterup-flags "--service-catalog"
-- Starting profile 'minishift'
-- Checking if https://github.com is reachable (using proxy: "No") ... OK
-- Checking if requested OpenShift version 'v3.9.0' is valid ... OK
-- Checking if requested OpenShift version 'v3.9.0' is supported ... OK
-- Checking if requested hypervisor 'xhyve' is supported on this platform ... OK
-- Checking if xhyve driver is installed ...
   Driver is available at /usr/local/bin/docker-machine-driver-xhyve
   Checking for setuid bit ... OK
-- Checking the ISO URL ... OK
-- Checking if provided oc flags are supported ... Flag 'extra-clusterup-flags' is not supported for oc version v3.9.0. Use 'openshift-version' flag to select a different version of OpenShift.
FAIL
Provided oc flag not supported
```
With this PR, this error will not come.

### CODE REVIEW

**Comment by gbraad** [comment]
Besides, wasn't @praveenkumar assigned to this task?

**Comment by LalatenduMohanty** [comment]
> a skip option needs to be added for the artifact checks

It was work in progress. Please check the PR now.

**Comment by LalatenduMohanty** [comment]
> Besides, wasn't @praveenkumar assigned to this task?

I was looking in to the code anyway and @praveenkumar has said it is fine if I can find the fix. Please check the IRC discussion.

**Comment by LalatenduMohanty** [comment]
Also I am going to add an integration test for this.

File: cmd/minishift/cmd/config/config.go [hunk 1]
```diff
@@ -123,6 +123,10 @@ var (
 	SkipCheckOpenShiftRelease = createConfigSetting("skip-check-openshift-release", SetBool, nil, nil, true, nil)
 	WarnCheckOpenShiftRelease = createConfigSetting("warn-check-openshift-release", SetBool, nil, nil, true, false)
 
+	// Pre-flight checks for artifacts (before start)
+	SkipCheckOcFlag = createConfigSetting("skip-check-oc-flags", SetBool, nil, nil, true, nil)
```
Comment (gbraad) [inline cmd/minishift/cmd/config/config.go]: check-clusterup-flags?

File: cmd/minishift/cmd/artifact_preflight.go [hunk 2]
```diff
@@ -39,21 +46,40 @@ type artifactCheckFunc func() bool
 // the returned status in a standardized way. If the test fails and returns a
 // false, the application will exit with errorMessage to describe what the
 // cause is.
-func artifactsCheckSucceedsOrFails(execute artifactCheckFunc, message string, errorMessage string) {
+func ocFlagCheckSucceedsOrFails(configNameOverrideIfSkipped string, execute artifactCheckFunc,
```
Comment (gbraad) [inline cmd/minishift/cmd/artifact_preflight.go]: It would now be a duplicate function of what already exists in preflight.go. see no additional value in having two functions doing the same. Since they are in the same package, no reason not to use it.

File: test/integration/features/flags.feature [hunk 3]
```diff
@@ -50,3 +50,11 @@ Feature: Flags
     Given Minishift has state "Running"
      When executing "minishift delete --force" succeeds
      Then Minishift should have state "Does Not Exist"
+
+  Scenario: Starting Minishift with extra-clusterup-flags
+    Given Minishift has state "Does Not Exist"
+      And image caching is disabled
+     When executing " MINISHIFT_ENABLE_EXPERIMENTAL=y minishift start --extra-clusterup-flags "--service-catalog" succeeds
```
Comment (gbraad) [inline test/integration/features/flags.feature]: :+1

File: cmd/minishift/cmd/artifact_preflight.go [hunk 4]
```diff
@@ -29,7 +29,14 @@ import (
 
 // preflightChecksForArtifacts is executed once artifacts are cached.
 func preflightChecksForArtifacts() {
-	artifactsCheckSucceedsOrFails(checkOcFlag, "Checking if provided oc flags are supported", "Provided oc flag not supported")
+
+	// checking if the flags provided during start are supported by the oc binary
+	ocFlagCheckSucceedsOrFails(
```
Comment (praveenkumar) [inline cmd/minishift/cmd/artifact_preflight.go]: @LalatenduMohanty how about using the following function instead of duplicating? Then you can also get rid of that `ocFlagCheckSucceedsOrFails` function also and there will be no duplication.

```golang
// checking if the flags provided during start are supported by the oc binary
	preflightCheckSucceedsOrFails(
		configCmd.SkipCheckOcFlag.Name,
		checkOcFlag,
		"Checking if provided oc flags are supported",
		configCmd.WarnCheckOcFlag.Name,
		"Provided oc flag not supported")
```

**Comment by praveenkumar** [comment]
@LalatenduMohanty Looks like integration test is also failing for this as unidentified test

```
20:44:18 1276 steps (1270 passed, 1 failed, 1 undefined, 4 skipped)
20:44:18 1h34m6.753646495s
20:44:18 
20:44:18 You can implement step definitions for undefined steps with these snippets:
20:44:18 
20:44:18 func executingServicecatalogSucceeds(arg1 string) error {
20:44:18 	return godog.ErrPending
20:44:18 }
20:44:18 
20:44:18 func FeatureContext(s *godog.Suite) {
20:44:18 	s.Step(`^executing "([^"]*)"--service-catalog" succeeds$`, executingServicecatalogSucceeds)
20:44:18 }
20:44:18 
```

File: cmd/minishift/cmd/artifact_preflight.go (hunk 4 above)
Comment (gbraad) [reply cmd/minishift/cmd/artifact_preflight.go]: That's two with the same comment

Comment (LalatenduMohanty) [reply cmd/minishift/cmd/artifact_preflight.go]: Right I should have reused the function. Will fix it.

Comment (LalatenduMohanty) [reply cmd/minishift/cmd/artifact_preflight.go]: > That's two with the same comment

@gbraad Sorry did not get you. What do you want to say?

File: cmd/minishift/cmd/artifact_preflight.go (hunk 2 above)
Comment (LalatenduMohanty) [reply cmd/minishift/cmd/artifact_preflight.go]: +1 for preflight_artifacts.go

**Comment by LalatenduMohanty** [comment]
> @LalatenduMohanty Looks like integration test is also failing for this as unidentified test

Looks like it needs more work.

File: cmd/minishift/cmd/preflight_artifacts.go [hunk 5]
```diff
@@ -22,38 +22,34 @@ import (
...
-
 // checkOcFlag checks if provided oc flags are supported
 func checkOcFlag() bool {
 	clusterUpParams := determineInitialClusterupParameters()
 	for _, key := range clusterUpParams {
+
+		// --extra-clusterup-flags is a minishift flag
+		if key == configCmd.ExtraClusterUpFlags.Name {
+			continue
+		}
```
Comment (praveenkumar) [inline cmd/minishift/cmd/preflight_artifacts.go]: :+1:

File: cmd/minishift/cmd/preflight_artifacts.go [hunk 6]
```diff
@@ -22,38 +22,34 @@ import (
...
 	flag "github.com/spf13/pflag"
 	"github.com/spf13/viper"
 )
 
 // preflightChecksForArtifacts is executed once artifacts are cached.
 func preflightChecksForArtifacts() {
-	artifactsCheckSucceedsOrFails(checkOcFlag, "Checking if provided oc flags are supported", "Provided oc flag not supported")
+
+	// checking if the flags provided during start are supported by the oc binary
+	preflightCheckSucceedsOrFails(
```
Comment (praveenkumar) [inline cmd/minishift/cmd/preflight_artifacts.go]: :+1:

**Comment by LalatenduMohanty** [comment]
@gbraad @praveenkumar PR is updated now.

File: cmd/minishift/cmd/config/config.go [hunk 7]
```diff
@@ -123,6 +123,10 @@ var (
 	SkipCheckOpenShiftRelease = createConfigSetting("skip-check-openshift-release", SetBool, nil, nil, true, nil)
 	WarnCheckOpenShiftRelease = createConfigSetting("warn-check-openshift-release", SetBool, nil, nil, true, false)
 
+	// Pre-flight checks for artifacts (before start)
```
Comment (budhrg) [inline cmd/minishift/cmd/config/config.go]: Artifacts is too general term here. It should be 
```
// Pre-flight checks for oc (before start)
```

File: cmd/minishift/cmd/preflight_artifacts.go [hunk 8]
```diff
@@ -22,38 +22,29 @@ import (
...
+		configCmd.WarnCheckClusterUpFlag.Name,
+		"Provided oc flag not supported")
 }
 
 // checkOcFlag checks if provided oc flags are supported
 func checkOcFlag() bool {
 	clusterUpParams := determineInitialClusterupParameters()
 	for _, key := range clusterUpParams {
+
+		// --extra-clusterup-flags is a minishift flag
```
Comment (budhrg) [inline cmd/minishift/cmd/preflight_artifacts.go]: This comment reads incomplete. Do you mean `// check --extra-clusterup-flags flag presence` ?

Comment (gbraad) [reply cmd/minishift/cmd/preflight_artifacts.go]: it is informative... meaning that `--extra` is NOT an `oc cluster up` flag.

No need to be addressed

File: cmd/minishift/cmd/config/config.go (hunk 7 above)
Comment (gbraad) [reply cmd/minishift/cmd/config/config.go]: good enough...

pre-flight checks refactor is coming anyway...

Comment (LalatenduMohanty) [reply cmd/minishift/cmd/config/config.go]: The general term is intentional here as the section is for artifacts and this point we have only for oc but in future we might have more checks e.g. for ISO

File: cmd/minishift/cmd/preflight_artifacts.go (hunk 8 above)
Comment (LalatenduMohanty) [reply cmd/minishift/cmd/preflight_artifacts.go]: @budhrg  nope, the idea is, not to check for --extra-clusterup-flag as it as a minishift specific flag.

File: cmd/minishift/cmd/config/config.go (hunk 7 above)
Comment (praveenkumar) [reply cmd/minishift/cmd/config/config.go]: @budhrg it should be like that atm we only testing for `oc` but in future we also have some test for `iso`  and all those artifacts tests can be part of this group.

File: cmd/minishift/cmd/preflight_artifacts.go [hunk 9]
```diff
@@ -22,38 +22,29 @@ import (
...
+		configCmd.WarnCheckClusterUpFlag.Name,
+		"Provided oc flag not supported")
 }
 
 // checkOcFlag checks if provided oc flags are supported
 func checkOcFlag() bool {
 	clusterUpParams := determineInitialClusterupParameters()
 	for _, key := range clusterUpParams {
+
+		// no need to check for extra-clusterup-flags as it is a minishift specific flag
```
Comment (budhrg) [inline cmd/minishift/cmd/preflight_artifacts.go]: This does make sense as comment.

File: cmd/minishift/cmd/config/config.go (hunk 7 above)
Comment (budhrg) [reply cmd/minishift/cmd/config/config.go]: IMO, we can always refactor later but the current comment is too generalized. It might happen that pre-flight check for ISO may take time. It's always good to represent present. That's my opinion. 

This review comment shouldn't block PR though.

**Comment by gbraad** [comment]
branch is not up to date with master...

Also, @praveenkumar had approved before for the same content, but as 3 commits. so code-wise LGTM from him too.

I would like to see this merged ASAP

**Comment by budhrg** [comment]
> branch is not up to date with master...

Will be taken care by "Rebase and merge" button. 

> I would like to see this merged ASAP

Waiting for CI to complete.
