### PR TITLE
Issue #2189 Fix minishift update command

### LINKED ISSUE #2189: "minishift" update is failing
### General information

  * Minishift version: v1.15.0
  * OS: Linux / macOS / Windows
  * Hypervisor: KVM / xhyve / Hyper-V / VirtualBox

### Steps to reproduce

  1. Compile minishift from source after the commit from https://github.com/minishift/minishift/pull/2078
  2.  Change Makefile to keep minishift version less than v.1.15.0
  3.  run `minishift update`
 
### Actual
```
$ minishift update
A newer version of minishift is available.
Do you want to update from 1.14.0 to 1.15.0 now? [y/N]: y
Update failed: Directory '/Users/lmohanty/code/gocode/bin' binary doesn't have write permission.
Please fix the permission issue and try running the command again.
```

### PR DESCRIPTION
**Pull request by budhrg**
Fix #2189 

Test it as : 
```
# vim Makefile and change MINISHIFT_VERSION = 1.14.0
$ make
$ minishift update
```

### CODE REVIEW

File: pkg/util/utils.go [hunk 1]
```diff
@@ -187,10 +187,10 @@ func CommandExecutesSuccessfully(cmd string, args ...string) bool {
 func IsDirectoryWritable(path string) bool {
 	tmpFilePath := filepath.Join(path, "tmp")
 	_, err := os.Create(tmpFilePath)
-	defer os.Remove(tmpFilePath)
 	if err != nil {
 		return false
 	}
+	defer os.Remove(tmpFilePath)
```
Comment (anjannath) [inline pkg/util/utils.go]: Why move this line?

File: pkg/minishift/update/update.go [hunk 2]
```diff
@@ -81,7 +81,7 @@ func Update(latestVersion semver.Version) error {
 	var extName string
 
 	path, _ := osext.Executable()
-	if writable := util.IsDirectoryWritable(path); !writable {
+	if writable := util.IsDirectoryWritable(filepath.Dir(path)); !writable {
 		return fmt.Errorf("Directory '%s' binary doesn't have write permission.\nPlease fix the permission issue and try running the command again.", filepath.Dir(path))
```
[the remark this answers is not in the document]
Comment (LalatenduMohanty) [reply pkg/minishift/update/update.go]: We should remove the word `binary` from the sentence.

**Comment by anjannath** [comment]
LGTM :+1:

File: pkg/util/utils.go (hunk 1 above)
Comment (LalatenduMohanty) [reply pkg/util/utils.go]: @anjannath Because we should handle the error from the `os.Create` and then call anything else. It is just more logical.

File: pkg/minishift/update/update.go (hunk 2 above)
[the remark this answers is not in the document]
Comment (gbraad) [reply pkg/minishift/update/update.go]: not a big problem, but sure

File: pkg/util/utils.go (hunk 1 above)
Comment (gbraad) [reply pkg/util/utils.go]: it does not make sense to move it... defer is just acting like a queue

Comment (budhrg) [reply pkg/util/utils.go]: It is not having significant impact here but actually it does if we defer the function:
#### When defer is after error check
```
  _, err := os.Create("/usr/bin/tmp")
  if err != nil {
    fmt.Println("err before defer", err)
    return false
  }
  defer func(){
    fmt.Println("err in defer: ", err)
    os.Remove(tmpFilePath)
  }()

  # Output
  err before defer open /usr/bin/tmp: permission denied
```     

#### When defer is before error check
```
  _, err := os.Create("/usr/bin/tmp")
  defer func(){
    fmt.Println("err in defer: ", err)
    os.Remove(tmpFilePath)
    }()
  if err != nil {
    fmt.Println("err before defer", err)
    return false
  }

  # Output
  err before defer open /usr/bin/tmp: permission denied
  err in defer:  open /usr/bin/tmp: permission denied
```

Check https://play.golang.org/p/pluqU0OQlEq
