### PR TITLE
Issue #3203 Fix oauth token request token uri in console command

### LINKED ISSUE #3203: `minishift console --request-oauth-token` opens wrong uri for token request
### General information

  * Minishift version: 
  * OS: Linux / macOS / Windows
  * Hypervisor: KVM / xhyve / Hyper-V / VirtualBox

### Steps to reproduce

  1. Start the minishift
  2. Wait till it is successful
  3. Execute `minishift console --request-oauth-token`

### Expected
It should open the token request url in browser (_https://clusterip:8443/oauth/token/request_)
### Actual
opens the url _https://clusterip:8443/console/oauth/token/request_

### Logs

You can start Minishift with `minishift start --show-libmachine-logs -v5` to collect logs.
Please consider posting this on http://gist.github.com/ and post the link in the issue.

### PR DESCRIPTION
**Pull request by anjannath**
Fixes #3203 

Steps to test the pull request

  1. `minishift start`
  2. `minishift console --request-oauth-token`
  3. In the browser after logging in, you should see the token

### CODE REVIEW

**Comment by gbraad** [comment]
Any update? Do we wanna merge this?

**Comment by anjannath** [comment]
@gbraad I think we should merge this, although not many people use this flag to get the token, as we didn't see any other issues about it.

File: cmd/minishift/cmd/console.go [hunk 1]
```diff
@@ -82,6 +82,12 @@ func getHostUrl(api *libmachine.Client) string {
 	return url
 }
 
+func getTokenRequestUrl(api *libmachine.Client) string {
+	hostIP := getHostIp(api)
+	tokenUrl := fmt.Sprintf("https://%s:%d/%s", hostIP, constants.APIServerPort, "oauth/token/request")
+	return tokenUrl
+}
```
Comment (praveenkumar) [inline cmd/minishift/cmd/console.go]: 👍
