### PR TITLE
Issue #1203 Install default add-ons if addons directory is not present

### LINKED ISSUE #1203: Behaviour of automatic installation of addons
I have tried to run coolstore.feature test, which failed to me. The problem is that between runs of integration tests, the integration-test folder is not being deleted. Due to this fact the addons folder is not being populated by default addons - aka automatic installation of default addons. 

Question is: **In which cases we want minishift to automatically install addons?**

Currently it is:

- minishift home folder does not exist
- minishift home folder is completely empty

Should it also trigger automatic installation when "addons" folder is not present in minishift home? Now it just creates empty folder called "addons".

### PR DESCRIPTION
**Pull request by LalatenduMohanty**
Fixes #1203 

Signed-off-by: Lalatendu Mohanty <lmohanty@redhat.com>

### CODE REVIEW

File: cmd/minishift/cmd/root.go [hunk 1]
```diff
@@ -79,12 +79,12 @@ var RootCmd = &cobra.Command{
...
 		var (
-			err          error
-			isFreshStart bool
+			err                    error
+			isAddonInstallRequired bool
 		)
 
-		if !filehelper.Exists(constants.Minipath) || filehelper.IsEmptyDir(constants.Minipath) {
-			isFreshStart = true
+		if !filehelper.Exists(constants.MakeMiniPath("addons")) {
```
Comment (budhrg) [inline cmd/minishift/cmd/root.go]: @hferentschik , are we taking this path now instead of what we decided as part of PR https://github.com/minishift/minishift/pull/990.

Comment (hferentschik) [inline cmd/minishift/cmd/root.go]: Works for me. The big issue I am having with this code, is the use of constants.MakeMiniPath("addons"). This is really a misuse of the constants and very error prone. However we are not only doing this here, but for other paths as well. I am hoping to be able to address this once we have some sort of MinishiftPaths struct which gives typed access to the various paths in $MINISHIFT_HOME. AFAIK @LalatenduMohanty is creating this struct as part of the profile feature. 

I already see this code breaking due to this. Really we should have named these variables a long time ago in the constant files, e.g. constants.AddonPath or something. Same for the other paths. Using constants.MakeMiniPath("addons") is just wrong.

**Comment by hferentschik** [comment]
Merged, thanks.

File: cmd/minishift/cmd/root.go (hunk 1 above)
Comment (LalatenduMohanty) [inline cmd/minishift/cmd/root.go]: @hferentschik Yes, I will fix this as part of #126.
