### PR TITLE
Issue #1958 Fixing addon list display

### LINKED ISSUE #1958: Output of "minishift addon list" looks broken  in some cases
### General information

  * Minishift version:  minishift v1.12.0+838f4d50 (compiled from master head)
  * OS: Linux / macOS / Windows
  * Hypervisor: KVM / xhyve / Hyper-V / VirtualBox

### Steps to reproduce

  1.  Install the  ansible-service-broker from https://github.com/minishift/minishift-addons
  2.  Run `minishift addon list`

### Expected

The output should have proper spaces and tabs.

### Actual
```
$ minishift addon list
- admin-user     : disabled   P(0)
- ansible-service-broker: disabled   P(0)
- anyuid         : disabled   P(0)
- che            : disabled   P(0)
- registry-route : disabled   P(0)
- xpaas          : disabled   P(0)
```

### PR DESCRIPTION
**Pull request by LalatenduMohanty**
Fixes #1958 

Signed-off-by: Lalatendu Mohanty <lmohanty@redhat.com>

### CODE REVIEW

File: cmd/minishift/cmd/addon/addons_list.go [hunk 1]
```diff
@@ -88,14 +89,15 @@ func runListCommand(cmd *cobra.Command, args []string) {
...
+
 	for _, addon := range addOns {
 		description := strings.Join(addon.MetaData().Description(), fmt.Sprintf("\n%13s", " "))
-		addonTemplate := DisplayAddOn{addon.MetaData().Name(), description, stringFromStatus(addon.IsEnabled()), addon.GetPriority()}
-		err := template.Execute(writer, addonTemplate)
-		if err != nil {
-			atexit.ExitWithMessage(1, fmt.Sprintf("Error executing the template: %s", err.Error()))
-		}
+		addonInfo := DisplayAddOn{addon.MetaData().Name(), description, stringFromStatus(addon.IsEnabled()), addon.GetPriority()}
+		fmt.Fprintln(display, fmt.Sprintf("%s\t: %s P(%v)", addonInfo.Name, addonInfo.Status, addonInfo.Priority))
```
Comment (praveenkumar) [inline cmd/minishift/cmd/addon/addons_list.go]: You also need to update the integration test around it check the https://ci.centos.org/job/minishift-pr/3666/consoleFull basic feature is failing it.

File: cmd/minishift/cmd/addon/addons_list.go [hunk 2]
```diff
@@ -88,14 +89,15 @@ func runListCommand(cmd *cobra.Command, args []string) {
 func printAddOnList(manager *manager.AddOnManager, writer io.Writer, template *template.Template) {
 	addOns := manager.List()
 	sort.Sort(addon.ByStatusThenPriorityThenName(addOns))
+	display := new(tabwriter.Writer)
+	display.Init(os.Stdout, 0, 8, 0, '\t', 0)
+
 	for _, addon := range addOns {
 		description := strings.Join(addon.MetaData().Description(), fmt.Sprintf("\n%13s", " "))
```
Comment (anjannath) [inline cmd/minishift/cmd/addon/addons_list.go]: I don't see the description printed in the o/p, and also what is the difference between `fmt.Sprintf("\n%13s", " ")` vs. `fmt.Sprintf("\n%s", " ")` ?
