### PR TITLE
Issue #3170 Add preflight check for powershell and fix vmms check

### LINKED ISSUE #3170: Minishift unable to start Hyper-V on Windows 10 when PowerShell not on PATH (missing pre-flight)
### General information

  * Minishift version:  minishift v1.31.0+cfc599c
  * OS: Linux / macOS / Windows : Windows 10
  * Hypervisor: KVM / xhyve / Hyper-V / VirtualBox : Hyper-V

Everything being run as administrator and user is a part of HYPERV Admins and Administrator group both.

### Steps to reproduce

  1.  minishift config set hyperv-virtual-switch hypervext
  ### Expected
Should work 

### Actual

[Virtual Switch not found]

Also Minishift Starts gives below

c:\minishift>minishift start
-- Starting profile 'minishift'
-- Check if deprecated options are used ... OK
-- Checking if https://github.com is reachable ... OK
-- Checking if requested OpenShift version 'v3.11.0' is valid ... OK
-- Checking if requested OpenShift version 'v3.11.0' is supported ... OK
-- Checking if requested hypervisor 'hyperv' is supported on this platform ... OK
-- Checking if Hyper-V driver is installed ... FAIL
   See the 'Setting Up the Virtualization Environment' topic (https://docs.okd.io/latest/minishift/getting-started/setting-up-virtualization-environment.html) for more information

Power Shell Output
PS C:\minishift> (Hyper-V\Get-VMSwitch).Name
hypervext
DockerNAT
Default Switch

### Logs

You can start Minishift with `minishift start --show-libmachine-logs -v5` to collect logs.
Please consider posting this on http://gist.github.com/ and post the link in the issue.
 
** Logs are not seen in the current minishift folder when running above command. Where can this be located ?

### PR DESCRIPTION
**Pull request by anjannath**
Fixes #3170

### CODE REVIEW

File: cmd/minishift/cmd/start_preflight.go [hunk 1]
```diff
@@ -433,22 +439,22 @@ func checkHypervDriverSwitch() bool {
...
+	// check to see if a hypervisor is present. if hyper-v is installed and enabled,
 	checkHypervisorPresent := `@(Get-Wmiobject Win32_ComputerSystem).HypervisorPresent`
-
 	stdOut, _, _ := posh.Execute(checkHypervisorPresent)
 	if !strings.Contains(stdOut, "True") {
 		return false
 	}
 
+	// Check if Hyper-V's Virtual Machine Management Service is running
+	checkVmmsRunning := `@(Get-Service vmms).Status`
```
Comment (gbraad) [inline cmd/minishift/cmd/start_preflight.go]: :+1

File: cmd/minishift/cmd/start_preflight.go [hunk 2]
```diff
@@ -433,22 +439,22 @@ func checkHypervDriverSwitch() bool {
...
+	stdOut, _, _ = posh.Execute(checkVmmsRunning)
+	if strings.TrimSpace(stdOut) != "Running" {
```
Comment (gbraad) [inline cmd/minishift/cmd/start_preflight.go]: This might lead to a localization problem... can we test this?

File: cmd/minishift/cmd/start_preflight.go [hunk 3]
```diff
@@ -433,22 +439,22 @@ func checkHypervDriverSwitch() bool {
...
-	_, err := exec.LookPath("vmms.exe")
-	if err != nil {
-		return false
-	}
-
-	// check to see if a hypervisor is present. if hyper-v is installed and enabled,
 	posh := powershell.New()
 
+	// check to see if a hypervisor is present. if hyper-v is installed and enabled,
 	checkHypervisorPresent := `@(Get-Wmiobject Win32_ComputerSystem).HypervisorPresent`
```
Comment (anjannath) [inline cmd/minishift/cmd/start_preflight.go]: Did not change this..  as `Get-WindowsOptionalFeature -FeatureName Microsot-Hyper-V-All -Online` requires an elevated shell

File: cmd/minishift/cmd/start_preflight.go (hunk 2 above)
Comment (gbraad) [reply cmd/minishift/cmd/start_preflight.go]: I believe I forced the powershell session to be unaffected by localization.... or perhaps this was just a single test for the default switch name? Please check...

Comment (anjannath) [reply cmd/minishift/cmd/start_preflight.go]: Nice catch.. need to check this, in case of the default switch, we used the ID instead of the name to get around the localization problem

Comment (gbraad) [reply cmd/minishift/cmd/start_preflight.go]: right... but I also remember I added a check to docker/machine that sets the locale to work around their issue (as they use the name). I'll check the code...

Comment (gbraad) [reply cmd/minishift/cmd/start_preflight.go]: https://github.com/docker/machine/commit/5bc065d6eb72a0fccaf04e162ff3e723b7dc5b09

Oops... this sets the encoding output... but I am sure this can also be used for the locale. ;-)
