### PR TITLE
Issue #2541 Fix: Proxy env variable to be cleared upon restart

### LINKED ISSUE #2541: VM's environment variables are cleared upon restart
### General information

  * Minishift version: 1.20.0
  * OS: Linux
  * Hypervisor: VirtualBox

### Steps to reproduce

  1. `minishift delete`
  2. `minishift strat --vm-driver virtualbox`
  3. `minishift ssh env | sort > before_restart`
  4. `minishift stop`
  5. `minishift start --vm-driver virtualbox`
  6. `minishift ssh env | sort > after_restart`
  7. `diff before_start after_restart`

### Expected

There should be no differences (except for session variables perhaps).

### Actual

There are differences.

I believe this to be a fairly important issue as all proxy information is entirely missing on the second start. This is a big deal in corporate environments.

### PR DESCRIPTION
**Pull request by praveenkumar**
Fixes #2541

### CODE REVIEW

**Comment by LalatenduMohanty** [comment]
I am not able to test the PR till now

```
 $ minishift start --http-proxy http://163.172.86.64:3128
-- Starting profile 'minishift'
-- Using proxy for the setup
-- Check if deprecated options are used ... OK
-- Checking if https://github.com is reachable ... OK
-- Checking if requested OpenShift version 'v3.9.0' is valid ... SKIP
-- Checking if requested OpenShift version 'v3.9.0' is supported ... OK
-- Checking if requested hypervisor 'xhyve' is supported on this platform ... OK
-- Checking if xhyve driver is installed ...
   Driver is available at /usr/local/bin/docker-machine-driver-xhyve
   Checking for setuid bit ... OK
-- Checking the ISO URL ... OK
-- Checking if provided oc flags are supported ... OK
-- Starting the OpenShift cluster using 'xhyve' hypervisor ...
-- Minishift VM will be configured with ...
   Memory:    2 GB
   vCPUs :    2
   Disk size: 20 GB
-- Starting Minishift VM .................-- Setting proxy information ... OK
 OK
-- Checking for IP address ... OK
-- Checking for nameservers ... OK
-- Checking if external host is reachable from the Minishift VM ...
   Pinging 8.8.8.8 ... OK
-- Checking HTTP connectivity from the VM ...
   Retrieving http://minishift.io/index.html ... OK
-- Checking if persistent storage volume is mounted ... OK
-- Checking available disk space ... 1% used OK
   Importing 'docker.io/centos/php-71-centos7:latest' ....... OK
   Importing 'openshift/origin:v3.9.0' ........ OK
   Importing 'openshift/origin-docker-registry:v3.9.0' .. OK
   Importing 'openshift/origin-haproxy-router:v3.9.0' .. OK
-- OpenShift cluster will be configured with ...
   Version: v3.9.0
-- Pulling the Openshift Container Image . EXISTS
-- Copying oc binary from the OpenShift container image to VM .... OK
-- Starting OpenShift cluster ..................................................................................................................................................................................................Error during 'cluster up' execution: Error starting the cluster. ssh command error:
command : /var/lib/minishift/bin/oc cluster up --use-existing-config --routing-suffix 192.168.64.18.nip.io --host-data-dir /var/lib/minishift/hostdata --host-volumes-dir /var/lib/minishift/openshift.local.volumes --host-pv-dir /var/lib/minishift/openshift.local.pv --host-config-dir /var/lib/minishift/openshift.local.config --http-proxy http://163.172.86.64:3128 --no-proxy localhost,127.0.0.1,172.30.1.1 --public-hostname 192.168.64.18
err     : exit status 1
output  : Using nsenter mounter for OpenShift volumes
Using public hostname IP 192.168.64.18 as the host IP
Using 192.168.64.18 as the server IP
Starting OpenShift using openshift/origin:v3.9.0 ...
-- Starting OpenShift container ...
   Creating initial OpenShift configuration
   Starting OpenShift using container 'origin'
   Waiting for API server to start listening
   OpenShift server started
-- Adding default OAuthClient redirect URIs ... OK
-- Installing registry ...
   scc "privileged" added to: ["system:serviceaccount:default:registry"]
-- Installing router ... OK
-- Importing image streams ... OK
-- Importing templates ... OK
-- Importing internal templates ... OK
-- Installing web console ... FAIL
   Error: failed to start the web console server: timed out waiting for the condition
```

File: pkg/minikube/cluster/cluster.go [hunk 1]
```diff
@@ -94,6 +94,9 @@ func StartHost(api libmachine.API, config MachineConfig) (*host.Host, error) {
 		if err := api.Save(h); err != nil {
 			return nil, fmt.Errorf("Error saving started host: %s", err)
 		}
+		if err := setProxyToShell(config, h); err != nil {
+			return nil, err
```
Comment (LalatenduMohanty) [inline pkg/minikube/cluster/cluster.go]: @praveenkumar May be should add a meaningful string to the err e.g. `fmt.Errorf("Error setting proxy variables to shell : %s", err)
