### PR TITLE
Issue #1363 Fix iso-url to work with case sensitive urls.

### LINKED ISSUE #1363: shortnames broke case-sensitive iso-urls
Issue #1033 added a new function where it changes the parameter for iso-url to all lowercase. This breaks when file path is case sensitive.
```
func determineIsoUrl(iso string) string {
	iso = strings.ToLower(iso)  <<<--------------
	isoNotSpecified := ""

	switch iso {
	case minishiftConstants.B2dIsoAlias, isoNotSpecified:
		iso = constants.DefaultB2dIsoUrl
	case minishiftConstants.CentOsIsoAlias:
		iso = constants.DefaultCentOsIsoUrl
	default:
		if !(govalidator.IsURL(iso) || strings.HasPrefix(iso, "file:")) {
			fmt.Println()
			atexit.ExitWithMessage(1, unsupportedIsoUrlFormat)
		}
	}

	return iso <<<-------
}
```

### PR DESCRIPTION
**Pull request by anjannath**
Fix #1363 

Previously #1387, but i did force push on that branch because a build was failing, so that PR got closed automatically, Sorry for the mess!

### CODE REVIEW

File: cmd/minishift/cmd/start_test.go [hunk 1]
```diff
@@ -406,7 +406,9 @@ func TestDetermineIsoUrl(t *testing.T) {
 		{"CentOs", constants.DefaultCentOsIsoUrl},
 		{"http://my.custom.url/myiso.iso", "http://my.custom.url/myiso.iso"},
 		{"https://my.custom.url/myiso.iso", "https://my.custom.url/myiso.iso"},
+		{"https://my.custom.url/Myiso.iso", "https://my.custom.url/Myiso.iso"},
```
Comment (budhrg) [inline cmd/minishift/cmd/start_test.go]: :+1:

**Comment by budhrg** [comment]
LGTM :+1:
