### PR TITLE
Issue #3234 correct spelling mistake retriving=>retrieving

### LINKED ISSUE #3234: Retrieving is misspelled in "Retriving password from keychain"
### General information

  * Minishift version: v1.31.0+d06603e

### Steps to reproduce

  1. Install minishift
  2. minishift start
  3. Add your Red Hat Developer or Red Hat Subscription Management username.
  4. "Retriving password from keychain" instead of "Retrieving password from keychain" will appear on the screen.

### Expected

It is expected for Retrieving to be written correctly.

### Actual

Instead, it is written as "Retriving".

### Logs
```
-- Starting profile 'minishift'
-- Check if deprecated options are used ... OK
-- Checking if https://mirror.openshift.com is reachable ... OK
-- Checking if requested OpenShift version 'v3.11.82' is valid ... OK
-- Checking if requested OpenShift version 'v3.11.82' is supported ... OK
-- Checking if requested hypervisor 'kvm' is supported on this platform ... OK
-- Checking if KVM driver is installed ... 
   Driver is available at /usr/local/bin/docker-machine-driver-kvm ... 
   Checking driver binary is executable ... OK
-- Checking if Libvirt is installed ... OK
-- Checking if Libvirt default network is present ... OK
-- Checking if Libvirt default network is active ... OK
-- Checking the ISO URL ... OK
-- Checking if provided oc flags are supported ... OK
-- Starting the OpenShift cluster using 'kvm' hypervisor ...
-- Starting Minishift VM .......................... OK
-- Registering machine using subscription-manager
   Red Hat Developers or Red Hat Subscription Management (RHSM) username: --@ok.com
   Retriving password from keychain ... OK 
```

### PR DESCRIPTION
**Pull request by anjannath**
Fixes #3234

### CODE REVIEW

File: pkg/minishift/registration/redhat.go [hunk 1]
```diff
@@ -80,7 +80,7 @@ func (registrator *RedHatRegistrator) Register(param *RegistrationParameters) er
 			// request password (disallow empty value)
 			if param.Password == "" {
 				if i == 1 {
-					fmt.Printf("   Retriving password from keychain ...")
+					fmt.Printf("   Retrieving password from keychain ...")
```
Comment (praveenkumar) [inline pkg/minishift/registration/redhat.go]: 👍
