### PR TITLE
Issue #1527 Fix CentOS CI script to not fail when minibot URL is not reachable

### LINKED ISSUE #1527: Fix the CentOS CI script to not fail when the minibot URL is not reachable
Since, minibot is deployed in temporary servers till now which is causing the minibot service url inconsistent which in result make the build fail if url is inaccessible. Eg - https://ci.centos.org/job/minishift-release/74/console (v1.7.0 release build).

My suggestion is to remove the minibot notification from centos-ci and add again once we get the consistent place for minibot.

### PR DESCRIPTION
**Pull request by budhrg**
Fix #1527

### CODE REVIEW

File: centos_ci.sh [hunk 1]
```diff
@@ -291,7 +291,7 @@ function perform_release() {
   # Notify Minibot
   MESSAGE="Minishift v$RELEASE_VERSION successfully released by https://ci.centos.org/job/minishift-release/$BUILD_NUMBER."
   URL="https://github.com/$REPO_OWNER/minishift/releases/tag/v$RELEASE_VERSION"
-  curl http://minibot.19cf262c.svc.dockerapp.io:9009/hubot/centosci -H "Content-Type: application/json" -d '{"payload":{"status":"success","message":'"\"$MESSAGE\""',"url":'"\"$URL\""'}}'
+  curl http://minibot.19cf262c.svc.dockerapp.io:9009/hubot/centosci -H "Content-Type: application/json" -d '{"payload":{"status":"success","message":'"\"$MESSAGE\""',"url":'"\"$URL\""'}}' || true
```
Comment (LalatenduMohanty) [inline centos_ci.sh]: @budhrg Nitpicking, Please add a comment saying the build should not fail if it can not reach minibot.

**Comment by LalatenduMohanty** [comment]
Thanks
