### PR TITLE
Issue #1606 check for valid VM Driver during preflight

### LINKED ISSUE #1606: Supported hypervisor check for a platform needs to happen before preflight
On Linux I did the following

```
$ minishift start --vm-driver virtualbox --profile test2
-- Starting local OpenShift cluster using 'virtualbox' hypervisor ...
-- Minishift VM will be configured with ...
   Memory:    2 GB
   vCPUs :    2
   Disk size: 20 GB

   Downloading ISO 'https://github.com/minishift/minishift-b2d-iso/releases/download/v1.2.0/minishift-b2d.iso'
 0 B / 40.00 MiB [-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------]   0.00%^C
$ minishift start --vm-driver hyperv --profile test2
-- Checking if Hyper-V driver is installed ... panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x9b8e85]

goroutine 1 [running]:
github.com/minishift/minishift/pkg/minishift/shell/powershell.(*PowerShell).Execute(0xc420114f00, 0xb4dfca, 0x20, 0xc42029c0f0, 0xb46fe5, 0x18, 0x0)
        /var/workspaces/minishift/src/github.com/minishift/minishift/pkg/minishift/shell/powershell/powershell.go:34 +0x25
github.com/minishift/minishift/cmd/minishift/cmd.checkHypervDriverInstalled(0xb46fe5)
        /var/workspaces/minishift/src/github.com/minishift/minishift/cmd/minishift/cmd/start_preflight.go:304 +0x48
github.com/minishift/minishift/cmd/minishift/cmd.preflightCheckSucceedsOrFails(0xb46d75, 0x18, 0xb6c628, 0xb538ba, 0x27, 0x0, 0xb46fe5, 0x18, 0xb606d7, 0x42)
        /var/workspaces/minishift/src/github.com/minishift/minishift/cmd/minishift/cmd/start_preflight.go:154 +0x141
github.com/minishift/minishift/cmd/minishift/cmd.preflightChecksBeforeStartingHost()
        /var/workspaces/minishift/src/github.com/minishift/minishift/cmd/minishift/cmd/start_preflight.go:80 +0x14f
github.com/minishift/minishift/cmd/minishift/cmd.runStart(0xc4202fc000, 0xc420124840, 0x0, 0x4)
        /var/workspaces/minishift/src/github.com/minishift/minishift/cmd/minishift/cmd/start.go:161 +0x306
github.com/minishift/minishift/vendor/github.com/spf13/cobra.(*Command).execute(0xc4202fc000, 0xc4201247c0, 0x4, 0x4, 0xc4202fc000, 0xc4201247c0)
        /var/workspaces/minishift/src/github.com/minishift/minishift/vendor/github.com/spf13/cobra/command.go:651 +0x23a
github.com/minishift/minishift/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0x1075f00, 0x0, 0x2, 0xc420112b70)
        /var/workspaces/minishift/src/github.com/minishift/minishift/vendor/github.com/spf13/cobra/command.go:726 +0x339
github.com/minishift/minishift/vendor/github.com/spf13/cobra.(*Command).Execute(0x1075f00, 0xc4201f5f68, 0x9d1f82)
        /var/workspaces/minishift/src/github.com/minishift/minishift/vendor/github.com/spf13/cobra/command.go:685 +0x2b
github.com/minishift/minishift/cmd/minishift/cmd.Execute()
        /var/workspaces/minishift/src/github.com/minishift/minishift/cmd/minishift/cmd/root.go:139 +0x2d
main.main()
        /var/workspaces/minishift/src/github.com/minishift/minishift/cmd/minishift/main.go:26 +0x25
```

Linux will never be able to support xhyve or hyperv... this validations happens as part of the `startHost`. This needs to happen earlier.

### PR DESCRIPTION
**Pull request by anjannath**
Fixes #1606

### CODE REVIEW

**Comment by budhrg** [comment]
@anjannath , need rebase with master

**Comment by anjannath** [comment]
@budhrg Ohh.. my bad will do

File: cmd/minishift/cmd/start_preflight.go [hunk 1]
```diff
@@ -46,6 +47,11 @@ const (
 func preflightChecksBeforeStartingHost() {
 	driverErrorMessage := "See the 'Setting Up the Driver Plug-in' topic for more information"
 
+	err := validations.IsValidDriver("", viper.GetString(configCmd.VmDriver.Name))
```
Comment (gbraad) [inline cmd/minishift/cmd/start_preflight.go]: the `name` parameter does not have to be empty...
is it possible still wrap this in a preflightCheck function? As this will then be consistent with execution and reporting.

**Comment by gbraad** [comment]
The error message is in this case not clear enough. Either the initial message needs to mention we check platform support, or it needs to be in the error.

Will check this later in use and think a little... but suggestions welcomed.

**Comment by anjannath** [comment]
@gbraad How about we say 
```
checking support for xhyve driver ... FAIL
[Driver xhyve is not supported]
```
and on success
```
checking support for xhyve driver ... OK
```

**Comment by gbraad** [comment]
@anjannath 

```
-- Checking if requested hypervisor 'xhyve' is supported on this platform ... OK
```

```
-- Checking if requested hypervisor 'hyperv' is supported on this platform ... FAIL
   See the 'Setting Up the Driver Plug-in' topic for more information
```

It might be possible to re-use the error message here.

File: cmd/minishift/cmd/start_preflight.go [hunk 2]
```diff
@@ -459,3 +467,11 @@ func checkIsoUrl() bool {
 
 	return true
 }
+
+func checkVMDriver() bool {
+	err := validations.IsValidDriver("viper.GetString(configCmd.VmDriver.Name)", viper.GetString(configCmd.VmDriver.Name))
```
Comment (gbraad) [inline cmd/minishift/cmd/start_preflight.go]: `"viper.GetString(configCmd.VmDriver.Name)"`

```
validations.IsValidDriver(configCmd.VmDriver.Name, viper.GetString(configCmd.VmDriver.Name))
```

**Comment by LalatenduMohanty** [comment]
We are adding more pre-flight checks and hence adding more content to the console output and it will be a lot of messages in the console in future. May be we can group some of them. In case of success we should just print one message for many pre-flight checks, but for failure we can print the exact failure. @minishift/minishift-dev WDYT?

**Comment by gbraad** [comment]
@LalatenduMohanty consolidation can come when we have reached a more stable point. At the moment I believe this gives valuable feedback. But yes, in future we might only show when it fails...

**Comment by LalatenduMohanty** [comment]
Created #1617 for future tracking.

**Comment by gbraad** [comment]
@anjannath please rebase onto master

**Comment by anjannath** [comment]
@gbraad rebase done

**Comment by gbraad** [comment]
after CI passed I can merge? /cc @LalatenduMohanty

**Comment by LalatenduMohanty** [comment]
@gbraad Please feel free to merge.
