### PR TITLE
Issue #2696 Add maximum time limit to start and stop of Che workspaces

### LINKED ISSUE #2696: Che integration tests needs timeouts on individual steps
Migrated minishift-addons issue: https://github.com/minishift/minishift-addons/issues/127

> Currently when something goes wrong durring Che tests, the whole testsuite stops at the failing step and waits until whole test run timeouts (2 hours). Instead the steps for creation and starting of workspaces should have its own timeouts (10 minutes) and if that time is exceeded, step should fail and tests continue...

### PR DESCRIPTION
**Pull request by agajdosi**
Fixes #2696 

Steps to test the pull request

  1. make integration GODOG_OPTS=-tags=addon-che

You can lower maximum time in addon-che.feature to `1s` or `1ms` to see the behaviour when the scenario timeouts.

### CODE REVIEW

**Comment by agajdosi** [comment]
Tests passed in both Che features: https://ci.centos.org/job/minishift-pr/5347/console. Now switching Makefile back to the normal.

**Comment by LalatenduMohanty** [comment]
@agajdosi How to interpret the code coverage results? I am not sure why it says that `pkg/util/github/github.go` and `.../minishift/openshift/version/openshift_versions.go` are impacted.

File: test/integration/che/che-steps.go [hunk 1]
```diff
@@ -42,13 +42,13 @@ func FeatureContext(s *godog.Suite) {
...
 	s.Step(`^workspace should have state "([^"]*)"$`, cheAPIRunner.workspaceShouldHaveState)
 	s.Step(`^importing the sample project "([^"]*)" succeeds$`, cheAPIRunner.importingTheSampleProjectSucceeds)
 	s.Step(`^workspace should have (\d+) project$`, cheAPIRunner.workspaceShouldHaveProject)
 	s.Step(`^user runs command on sample "([^"]*)"$`, cheAPIRunner.userRunsCommandOnSample)
 	s.Step(`^exit code should be (\d+)$`, cheAPIRunner.exitCodeShouldBe)
-	s.Step(`^stopping a workspace succeeds$`, cheAPIRunner.stoppingWorkspaceSucceeds)
+	s.Step(`^stopping a workspace succeeds within "(\d+(?:ms|s|m))"$`, cheAPIRunner.stoppingWorkspaceSucceeds)
 	s.Step(`^workspace is removed$`, cheAPIRunner.workspaceIsRemoved)
 	s.Step(`^workspace removal should be successful$`, cheAPIRunner.workspaceRemovalShouldBeSuccessful)
 }
```
Comment (LalatenduMohanty) [inline test/integration/che/che-steps.go]: @agajdosi This comment is not for this PR but for future. I think the Che specific steps should be also be moved to `testsuite/testsuite.go`.  It is also way good to have all the steps in one place from long-term maintenance/readablity point of view.

File: test/integration/che/che-steps.go [hunk 2]
```diff
@@ -42,13 +42,13 @@ func FeatureContext(s *godog.Suite) {
 	s.Step(`^che api endpoint should not be empty$`, cheAPIRunner.cheApiEndpointShouldNotBeEmpty)
 	s.Step(`^user tries to get the stacks information$`, cheAPIRunner.weTryToGetTheStacksInformation)
 	s.Step(`^the stacks should not be empty$`, cheAPIRunner.theStacksShouldNotBeEmpty)
-	s.Step(`^starting a workspace with stack "([^"]*)" succeeds$`, cheAPIRunner.startingWorkspaceWithStackSucceeds)
+	s.Step(`^starting a workspace with stack "([^"]*)" succeeds within "(\d+(?:ms|s|m))"$`, cheAPIRunner.startingWorkspaceWithStackSucceeds)
```
Comment (LalatenduMohanty) [inline test/integration/che/che-steps.go]: :+1:

File: test/integration/che/cheAPI.go [hunk 3]
```diff
@@ -341,22 +341,30 @@ func (c *CheAPI) GetNumberOfProjects() (int, error) {
 	return len(data), nil
 }
 
-//BlockWorkspace blocks the given workspaceID until it has started
-func (c *CheAPI) BlockWorkspace(workspaceID, untilStatus string) error {
+//BlockWorkspace blocks the given workspaceID until it has given status
+func (c *CheAPI) BlockWorkspace(workspaceID string, expectedStatus string, maxTime string) error {
+	maxDuration, err := time.ParseDuration(maxTime)
```
Comment (LalatenduMohanty) [inline test/integration/che/cheAPI.go]: s/maxDuration/testDuration/

File: test/integration/che/che.go [hunk 4]
```diff
@@ -90,13 +90,13 @@ func (c *CheRunner) theStacksShouldNotBeEmpty() error {
 	return nil
 }
 
-func (c *CheRunner) startingWorkspaceWithStackSucceeds(stackName string) error {
+func (c *CheRunner) startingWorkspaceWithStackSucceeds(stackName string, maxTime string) error {
```
Comment (LalatenduMohanty) [inline test/integration/che/che.go]: suggestion s/maxTime/timeoutValue/

**Comment by agajdosi** [comment]
> How to interpret the code coverage results? I am not sure why it says that pkg/util/github/github.go and .../minishift/openshift/version/openshift_versions.go are impacted.

@LalatenduMohanty There is a problem I could not debug before and that is that for some reason, the coverage on master is different than on incoming PRs, e.g.: on incoming PR the coverage detected is 26.37%, however once the commit is merged to master it is then detected to be 28.14%. Thus it later looks that on each PR the coverage is going lower, because on master we have an extra +1.77%. When I try locally it is the same, I am not sure for now what is the reason for this  strange behaviour :(

File: test/integration/che/che.go (hunk 4 above)
Comment (LalatenduMohanty) [reply test/integration/che/che.go]: >     * timeout string, maxDuration time.Duration

+1. Sounds good to me.

**Comment by LalatenduMohanty** [comment]
>  When I try locally it is the same, I am not sure for now what is the reason for this strange behaviour :(

I guess we need to take a deeper look later about this or when time permits.

File: test/integration/che/che.go (hunk 4 above)
Comment (LalatenduMohanty) [reply test/integration/che/che.go]: @agajdosi Unless you want to make the variable names consistent, I am ok to merge as it is. Mostly because I can still accept the current names. Let me know.

Comment (agajdosi) [reply test/integration/che/che.go]: @LalatenduMohanty I have kept it consistent around Che test - using the timeout and maxDuration in one func. Rebased now, we can merge.
