### PR TITLE
Issue #2712 Fixing the exit code for oc context set during restart

### LINKED ISSUE #2712: minishift start should return non-zero exit code when it fails with error "could not set oc CLI context for 'minishift' profile"
### General information

  * Minishift version: 
  * OS: Linux / macOS / Windows
  * Hypervisor: KVM / xhyve / Hyper-V / VirtualBox

In the code we do not exit when we see the error  #2679 `could not set oc CLI context for 'minishift' profile` , hence `minishift start` returns `0` as the exit code when it should return a non-zero exit code.

```code
if isRestart {
			err = cmdUtil.SetOcContext(minishiftConfig.AllInstancesConfig.ActiveProfile)
			if err != nil {
				fmt.Println(fmt.Sprintf("Could not set oc CLI context for '%s' profile: %v", profileActions.GetActiveProfile(), err))
			}
		}
```

### Steps to reproduce

The issue #2679 is fixed now, but if you revert https://github.com/minishift/minishift/commit/6c901e8c31f35d021ee9423312c90b29e0c67040 you can reproduce this issue as it is only visible when code errors out  `Could not set oc CLI context for 'minishift' profile: Error during setting 'minishift' as active profile: The specified path to oc '' does not exist`. 

  1.  minishift start
  2. minishift stop
  3.  minishift start
  4.  echo $?

### Expected

```
$ minishift start
-- Starting profile 'minishift'
xxxxxxx
Starting OpenShift using openshift/origin:v3.9.0 ...
OpenShift server started.

The server is accessible via web console at:
    https://192.168.64.47:8443


Could not set oc CLI context for 'minishift' profile: Error during setting 'minishift' as active profile: The specified path to oc '' does not exist
```
```
$ echo $?
1
```
### Actual

```
$ minishift start
-- Starting profile 'minishift'
xxxxxxx
Starting OpenShift using openshift/origin:v3.9.0 ...
OpenShift server started.

The server is accessible via web console at:
    https://192.168.64.47:8443


Could not set oc CLI context for 'minishift' profile: Error during setting 'minishift' as active profile: The specified path to oc '' does not exist
```
```
$ echo $?
0
```

### PR DESCRIPTION
**Pull request by LalatenduMohanty**
Signed-off-by: Lalatendu Mohanty <lmohanty@redhat.com>

Fixes #2712 

Steps to test the pull request

  1.  git revert 6c901e8c31f35d021ee9423312c90b29e0c67040
  2.  make clean; make
  3. minishift start -> stop-> start
  4. echo $?

### CODE REVIEW

**Comment by LalatenduMohanty** [comment]
Test results with this PR. 

```
$ minishift start
-- Starting profile 'minishift'
xxxxxxxxxxxxxxxx
    https://192.168.64.3:8443


Could not set oc CLI context for 'minishift' profile: Error during setting 'minishift' as active profile: The specified path to oc '' does not exist

$ echo $?
1
```

File: cmd/minishift/cmd/start.go [hunk 1]
```diff
@@ -282,7 +282,7 @@ func runStart(cmd *cobra.Command, args []string) {
 		if isRestart {
 			err = cmdUtil.SetOcContext(minishiftConfig.AllInstancesConfig.ActiveProfile)
 			if err != nil {
-				fmt.Println(fmt.Sprintf("Could not set oc CLI context for '%s' profile: %v", profileActions.GetActiveProfile(), err))
+				atexit.ExitWithMessage(1, fmt.Sprintf("Could not set oc CLI context for '%s' profile: %v", profileActions.GetActiveProfile(), err))
```
Comment (praveenkumar) [inline cmd/minishift/cmd/start.go]: 👍
